package com.ridehub.promotion.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ConditionLocationItemAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConditionLocationItemAllPropertiesEquals(ConditionLocationItem expected, ConditionLocationItem actual) {
        assertConditionLocationItemAutoGeneratedPropertiesEquals(expected, actual);
        assertConditionLocationItemAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConditionLocationItemAllUpdatablePropertiesEquals(
        ConditionLocationItem expected,
        ConditionLocationItem actual
    ) {
        assertConditionLocationItemUpdatableFieldsEquals(expected, actual);
        assertConditionLocationItemUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConditionLocationItemAutoGeneratedPropertiesEquals(
        ConditionLocationItem expected,
        ConditionLocationItem actual
    ) {
        assertThat(actual)
            .as("Verify ConditionLocationItem auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConditionLocationItemUpdatableFieldsEquals(ConditionLocationItem expected, ConditionLocationItem actual) {
        assertThat(actual)
            .as("Verify ConditionLocationItem relevant properties")
            .satisfies(a -> assertThat(a.getProvinceId()).as("check provinceId").isEqualTo(expected.getProvinceId()))
            .satisfies(a -> assertThat(a.getDistrictId()).as("check districtId").isEqualTo(expected.getDistrictId()))
            .satisfies(a -> assertThat(a.getWardId()).as("check wardId").isEqualTo(expected.getWardId()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()))
            .satisfies(a -> assertThat(a.getIsDeleted()).as("check isDeleted").isEqualTo(expected.getIsDeleted()))
            .satisfies(a -> assertThat(a.getDeletedAt()).as("check deletedAt").isEqualTo(expected.getDeletedAt()))
            .satisfies(a -> assertThat(a.getDeletedBy()).as("check deletedBy").isEqualTo(expected.getDeletedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConditionLocationItemUpdatableRelationshipsEquals(
        ConditionLocationItem expected,
        ConditionLocationItem actual
    ) {
        assertThat(actual)
            .as("Verify ConditionLocationItem relationships")
            .satisfies(a -> assertThat(a.getCondition()).as("check condition").isEqualTo(expected.getCondition()));
    }
}
