package com.ridehub.promotion.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ConditionByRouteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConditionByRouteAllPropertiesEquals(ConditionByRoute expected, ConditionByRoute actual) {
        assertConditionByRouteAutoGeneratedPropertiesEquals(expected, actual);
        assertConditionByRouteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConditionByRouteAllUpdatablePropertiesEquals(ConditionByRoute expected, ConditionByRoute actual) {
        assertConditionByRouteUpdatableFieldsEquals(expected, actual);
        assertConditionByRouteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConditionByRouteAutoGeneratedPropertiesEquals(ConditionByRoute expected, ConditionByRoute actual) {
        assertThat(actual)
            .as("Verify ConditionByRoute auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConditionByRouteUpdatableFieldsEquals(ConditionByRoute expected, ConditionByRoute actual) {
        assertThat(actual)
            .as("Verify ConditionByRoute relevant properties")
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()))
            .satisfies(a -> assertThat(a.getIsDeleted()).as("check isDeleted").isEqualTo(expected.getIsDeleted()))
            .satisfies(a -> assertThat(a.getDeletedAt()).as("check deletedAt").isEqualTo(expected.getDeletedAt()))
            .satisfies(a -> assertThat(a.getDeletedBy()).as("check deletedBy").isEqualTo(expected.getDeletedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConditionByRouteUpdatableRelationshipsEquals(ConditionByRoute expected, ConditionByRoute actual) {
        assertThat(actual)
            .as("Verify ConditionByRoute relationships")
            .satisfies(a -> assertThat(a.getPromotion()).as("check promotion").isEqualTo(expected.getPromotion()));
    }
}
