package com.ridehub.promotion.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FilePromotionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFilePromotionAllPropertiesEquals(FilePromotion expected, FilePromotion actual) {
        assertFilePromotionAutoGeneratedPropertiesEquals(expected, actual);
        assertFilePromotionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFilePromotionAllUpdatablePropertiesEquals(FilePromotion expected, FilePromotion actual) {
        assertFilePromotionUpdatableFieldsEquals(expected, actual);
        assertFilePromotionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFilePromotionAutoGeneratedPropertiesEquals(FilePromotion expected, FilePromotion actual) {
        assertThat(actual)
            .as("Verify FilePromotion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFilePromotionUpdatableFieldsEquals(FilePromotion expected, FilePromotion actual) {
        assertThat(actual)
            .as("Verify FilePromotion relevant properties")
            .satisfies(a -> assertThat(a.getBucket()).as("check bucket").isEqualTo(expected.getBucket()))
            .satisfies(a -> assertThat(a.getObjectKey()).as("check objectKey").isEqualTo(expected.getObjectKey()))
            .satisfies(a -> assertThat(a.getContentType()).as("check contentType").isEqualTo(expected.getContentType()))
            .satisfies(a -> assertThat(a.getSize()).as("check size").isEqualTo(expected.getSize()))
            .satisfies(a -> assertThat(a.getIsBanner()).as("check isBanner").isEqualTo(expected.getIsBanner()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()))
            .satisfies(a -> assertThat(a.getIsDeleted()).as("check isDeleted").isEqualTo(expected.getIsDeleted()))
            .satisfies(a -> assertThat(a.getDeletedAt()).as("check deletedAt").isEqualTo(expected.getDeletedAt()))
            .satisfies(a -> assertThat(a.getDeletedBy()).as("check deletedBy").isEqualTo(expected.getDeletedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFilePromotionUpdatableRelationshipsEquals(FilePromotion expected, FilePromotion actual) {
        assertThat(actual)
            .as("Verify FilePromotion relationships")
            .satisfies(a -> assertThat(a.getPromotion()).as("check promotion").isEqualTo(expected.getPromotion()));
    }
}
