package com.ticketsystem.booking.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PassengerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPassengerAllPropertiesEquals(Passenger expected, Passenger actual) {
        assertPassengerAutoGeneratedPropertiesEquals(expected, actual);
        assertPassengerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPassengerAllUpdatablePropertiesEquals(Passenger expected, Passenger actual) {
        assertPassengerUpdatableFieldsEquals(expected, actual);
        assertPassengerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPassengerAutoGeneratedPropertiesEquals(Passenger expected, Passenger actual) {
        assertThat(actual)
            .as("Verify Passenger auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPassengerUpdatableFieldsEquals(Passenger expected, Passenger actual) {
        assertThat(actual)
            .as("Verify Passenger relevant properties")
            .satisfies(a -> assertThat(a.getSeatId()).as("check seatId").isEqualTo(expected.getSeatId()))
            .satisfies(a -> assertThat(a.getFirstName()).as("check firstName").isEqualTo(expected.getFirstName()))
            .satisfies(a -> assertThat(a.getLastName()).as("check lastName").isEqualTo(expected.getLastName()))
            .satisfies(a -> assertThat(a.getIdNumber()).as("check idNumber").isEqualTo(expected.getIdNumber()))
            .satisfies(a -> assertThat(a.getDateOfBirth()).as("check dateOfBirth").isEqualTo(expected.getDateOfBirth()))
            .satisfies(a -> assertThat(a.getNationality()).as("check nationality").isEqualTo(expected.getNationality()))
            .satisfies(a -> assertThat(a.getTicketNumber()).as("check ticketNumber").isEqualTo(expected.getTicketNumber()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPassengerUpdatableRelationshipsEquals(Passenger expected, Passenger actual) {
        assertThat(actual)
            .as("Verify Passenger relationships")
            .satisfies(a -> assertThat(a.getBooking()).as("check booking").isEqualTo(expected.getBooking()));
    }
}
