package com.ridehub.route.domain;

import static com.ridehub.route.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class PricingTemplateAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPricingTemplateAllPropertiesEquals(PricingTemplate expected, PricingTemplate actual) {
        assertPricingTemplateAutoGeneratedPropertiesEquals(expected, actual);
        assertPricingTemplateAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPricingTemplateAllUpdatablePropertiesEquals(PricingTemplate expected, PricingTemplate actual) {
        assertPricingTemplateUpdatableFieldsEquals(expected, actual);
        assertPricingTemplateUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPricingTemplateAutoGeneratedPropertiesEquals(PricingTemplate expected, PricingTemplate actual) {
        assertThat(actual)
            .as("Verify PricingTemplate auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPricingTemplateUpdatableFieldsEquals(PricingTemplate expected, PricingTemplate actual) {
        assertThat(actual)
            .as("Verify PricingTemplate relevant properties")
            .satisfies(a -> assertThat(a.getVehicleType()).as("check vehicleType").isEqualTo(expected.getVehicleType()))
            .satisfies(a -> assertThat(a.getSeatType()).as("check seatType").isEqualTo(expected.getSeatType()))
            .satisfies(a -> assertThat(a.getOccasionType()).as("check occasionType").isEqualTo(expected.getOccasionType()))
            .satisfies(a ->
                assertThat(a.getBaseFare()).as("check baseFare").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getBaseFare())
            )
            .satisfies(a ->
                assertThat(a.getVehicleFactor())
                    .as("check vehicleFactor")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getVehicleFactor())
            )
            .satisfies(a ->
                assertThat(a.getFloorFactor())
                    .as("check floorFactor")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getFloorFactor())
            )
            .satisfies(a ->
                assertThat(a.getSeatFactor())
                    .as("check seatFactor")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getSeatFactor())
            )
            .satisfies(a ->
                assertThat(a.getOccasionFactor())
                    .as("check occasionFactor")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getOccasionFactor())
            )
            .satisfies(a ->
                assertThat(a.getFinalPrice())
                    .as("check finalPrice")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getFinalPrice())
            )
            .satisfies(a -> assertThat(a.getValidFrom()).as("check validFrom").isEqualTo(expected.getValidFrom()))
            .satisfies(a -> assertThat(a.getValidTo()).as("check validTo").isEqualTo(expected.getValidTo()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()))
            .satisfies(a -> assertThat(a.getIsDeleted()).as("check isDeleted").isEqualTo(expected.getIsDeleted()))
            .satisfies(a -> assertThat(a.getDeletedAt()).as("check deletedAt").isEqualTo(expected.getDeletedAt()))
            .satisfies(a -> assertThat(a.getDeletedBy()).as("check deletedBy").isEqualTo(expected.getDeletedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPricingTemplateUpdatableRelationshipsEquals(PricingTemplate expected, PricingTemplate actual) {
        assertThat(actual)
            .as("Verify PricingTemplate relationships")
            .satisfies(a -> assertThat(a.getRoute()).as("check route").isEqualTo(expected.getRoute()));
    }
}
