package com.ridehub.route.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProvinceAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProvinceAllPropertiesEquals(Province expected, Province actual) {
        assertProvinceAutoGeneratedPropertiesEquals(expected, actual);
        assertProvinceAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProvinceAllUpdatablePropertiesEquals(Province expected, Province actual) {
        assertProvinceUpdatableFieldsEquals(expected, actual);
        assertProvinceUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProvinceAutoGeneratedPropertiesEquals(Province expected, Province actual) {
        assertThat(actual)
            .as("Verify Province auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProvinceUpdatableFieldsEquals(Province expected, Province actual) {
        assertThat(actual)
            .as("Verify Province relevant properties")
            .satisfies(a -> assertThat(a.getProvinceCode()).as("check provinceCode").isEqualTo(expected.getProvinceCode()))
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getNameEn()).as("check nameEn").isEqualTo(expected.getNameEn()))
            .satisfies(a -> assertThat(a.getFullName()).as("check fullName").isEqualTo(expected.getFullName()))
            .satisfies(a -> assertThat(a.getFullNameEn()).as("check fullNameEn").isEqualTo(expected.getFullNameEn()))
            .satisfies(a -> assertThat(a.getCodeName()).as("check codeName").isEqualTo(expected.getCodeName()))
            .satisfies(a ->
                assertThat(a.getAdministrativeUnitId()).as("check administrativeUnitId").isEqualTo(expected.getAdministrativeUnitId())
            )
            .satisfies(a ->
                assertThat(a.getAdministrativeRegionId()).as("check administrativeRegionId").isEqualTo(expected.getAdministrativeRegionId())
            )
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()))
            .satisfies(a -> assertThat(a.getIsDeleted()).as("check isDeleted").isEqualTo(expected.getIsDeleted()))
            .satisfies(a -> assertThat(a.getDeletedAt()).as("check deletedAt").isEqualTo(expected.getDeletedAt()))
            .satisfies(a -> assertThat(a.getDeletedBy()).as("check deletedBy").isEqualTo(expected.getDeletedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProvinceUpdatableRelationshipsEquals(Province expected, Province actual) {
        // empty method
    }
}
