package com.ridehub.route.domain;

import static com.ridehub.route.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ScheduleOccasionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScheduleOccasionAllPropertiesEquals(ScheduleOccasion expected, ScheduleOccasion actual) {
        assertScheduleOccasionAutoGeneratedPropertiesEquals(expected, actual);
        assertScheduleOccasionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScheduleOccasionAllUpdatablePropertiesEquals(ScheduleOccasion expected, ScheduleOccasion actual) {
        assertScheduleOccasionUpdatableFieldsEquals(expected, actual);
        assertScheduleOccasionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScheduleOccasionAutoGeneratedPropertiesEquals(ScheduleOccasion expected, ScheduleOccasion actual) {
        assertThat(actual)
            .as("Verify ScheduleOccasion auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScheduleOccasionUpdatableFieldsEquals(ScheduleOccasion expected, ScheduleOccasion actual) {
        assertThat(actual)
            .as("Verify ScheduleOccasion relevant properties")
            .satisfies(a -> assertThat(a.getOccasion()).as("check occasion").isEqualTo(expected.getOccasion()))
            .satisfies(a ->
                assertThat(a.getOccasionFactor())
                    .as("check occasionFactor")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getOccasionFactor())
            )
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()))
            .satisfies(a -> assertThat(a.getIsDeleted()).as("check isDeleted").isEqualTo(expected.getIsDeleted()))
            .satisfies(a -> assertThat(a.getDeletedAt()).as("check deletedAt").isEqualTo(expected.getDeletedAt()))
            .satisfies(a -> assertThat(a.getDeletedBy()).as("check deletedBy").isEqualTo(expected.getDeletedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertScheduleOccasionUpdatableRelationshipsEquals(ScheduleOccasion expected, ScheduleOccasion actual) {
        // empty method
    }
}
