package com.ridehub.route.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SeatMapAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeatMapAllPropertiesEquals(SeatMap expected, SeatMap actual) {
        assertSeatMapAutoGeneratedPropertiesEquals(expected, actual);
        assertSeatMapAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeatMapAllUpdatablePropertiesEquals(SeatMap expected, SeatMap actual) {
        assertSeatMapUpdatableFieldsEquals(expected, actual);
        assertSeatMapUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeatMapAutoGeneratedPropertiesEquals(SeatMap expected, SeatMap actual) {
        assertThat(actual)
            .as("Verify SeatMap auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeatMapUpdatableFieldsEquals(SeatMap expected, SeatMap actual) {
        assertThat(actual)
            .as("Verify SeatMap relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()))
            .satisfies(a -> assertThat(a.getIsDeleted()).as("check isDeleted").isEqualTo(expected.getIsDeleted()))
            .satisfies(a -> assertThat(a.getDeletedAt()).as("check deletedAt").isEqualTo(expected.getDeletedAt()))
            .satisfies(a -> assertThat(a.getDeletedBy()).as("check deletedBy").isEqualTo(expected.getDeletedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSeatMapUpdatableRelationshipsEquals(SeatMap expected, SeatMap actual) {
        // empty method
    }
}
