/*
 * Ms Booking API
 * Ms Booking API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.msbooking.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * InvoiceDTO
 */
@JsonPropertyOrder({
  InvoiceDTO.JSON_PROPERTY_ID,
  InvoiceDTO.JSON_PROPERTY_INVOICE_NO,
  InvoiceDTO.JSON_PROPERTY_ISSUED_AT,
  InvoiceDTO.JSON_PROPERTY_GROSS_AMOUNT,
  InvoiceDTO.JSON_PROPERTY_VAT_AMOUNT,
  InvoiceDTO.JSON_PROPERTY_NET_AMOUNT,
  InvoiceDTO.JSON_PROPERTY_CREATED_AT,
  InvoiceDTO.JSON_PROPERTY_UPDATED_AT,
  InvoiceDTO.JSON_PROPERTY_IS_DELETED,
  InvoiceDTO.JSON_PROPERTY_DELETED_AT,
  InvoiceDTO.JSON_PROPERTY_DELETED_BY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class InvoiceDTO {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_INVOICE_NO = "invoiceNo";
  @jakarta.annotation.Nonnull
  private String invoiceNo;

  public static final String JSON_PROPERTY_ISSUED_AT = "issuedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime issuedAt;

  public static final String JSON_PROPERTY_GROSS_AMOUNT = "grossAmount";
  @jakarta.annotation.Nullable
  private BigDecimal grossAmount;

  public static final String JSON_PROPERTY_VAT_AMOUNT = "vatAmount";
  @jakarta.annotation.Nullable
  private BigDecimal vatAmount;

  public static final String JSON_PROPERTY_NET_AMOUNT = "netAmount";
  @jakarta.annotation.Nullable
  private BigDecimal netAmount;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  @jakarta.annotation.Nullable
  private Boolean isDeleted;

  public static final String JSON_PROPERTY_DELETED_AT = "deletedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime deletedAt;

  public static final String JSON_PROPERTY_DELETED_BY = "deletedBy";
  @jakarta.annotation.Nullable
  private UUID deletedBy;

  public InvoiceDTO() {
  }

  public InvoiceDTO id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }


  public InvoiceDTO invoiceNo(@jakarta.annotation.Nonnull String invoiceNo) {
    
    this.invoiceNo = invoiceNo;
    return this;
  }

  /**
   * Get invoiceNo
   * @return invoiceNo
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_INVOICE_NO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getInvoiceNo() {
    return invoiceNo;
  }


  @JsonProperty(JSON_PROPERTY_INVOICE_NO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setInvoiceNo(@jakarta.annotation.Nonnull String invoiceNo) {
    this.invoiceNo = invoiceNo;
  }


  public InvoiceDTO issuedAt(@jakarta.annotation.Nullable OffsetDateTime issuedAt) {
    
    this.issuedAt = issuedAt;
    return this;
  }

  /**
   * Get issuedAt
   * @return issuedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ISSUED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getIssuedAt() {
    return issuedAt;
  }


  @JsonProperty(JSON_PROPERTY_ISSUED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIssuedAt(@jakarta.annotation.Nullable OffsetDateTime issuedAt) {
    this.issuedAt = issuedAt;
  }


  public InvoiceDTO grossAmount(@jakarta.annotation.Nullable BigDecimal grossAmount) {
    
    this.grossAmount = grossAmount;
    return this;
  }

  /**
   * Get grossAmount
   * @return grossAmount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GROSS_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getGrossAmount() {
    return grossAmount;
  }


  @JsonProperty(JSON_PROPERTY_GROSS_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGrossAmount(@jakarta.annotation.Nullable BigDecimal grossAmount) {
    this.grossAmount = grossAmount;
  }


  public InvoiceDTO vatAmount(@jakarta.annotation.Nullable BigDecimal vatAmount) {
    
    this.vatAmount = vatAmount;
    return this;
  }

  /**
   * Get vatAmount
   * @return vatAmount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VAT_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getVatAmount() {
    return vatAmount;
  }


  @JsonProperty(JSON_PROPERTY_VAT_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVatAmount(@jakarta.annotation.Nullable BigDecimal vatAmount) {
    this.vatAmount = vatAmount;
  }


  public InvoiceDTO netAmount(@jakarta.annotation.Nullable BigDecimal netAmount) {
    
    this.netAmount = netAmount;
    return this;
  }

  /**
   * Get netAmount
   * @return netAmount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NET_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getNetAmount() {
    return netAmount;
  }


  @JsonProperty(JSON_PROPERTY_NET_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNetAmount(@jakarta.annotation.Nullable BigDecimal netAmount) {
    this.netAmount = netAmount;
  }


  public InvoiceDTO createdAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public InvoiceDTO updatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public InvoiceDTO isDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    
    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * Get isDeleted
   * @return isDeleted
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsDeleted() {
    return isDeleted;
  }


  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }


  public InvoiceDTO deletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    
    this.deletedAt = deletedAt;
    return this;
  }

  /**
   * Get deletedAt
   * @return deletedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDeletedAt() {
    return deletedAt;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    this.deletedAt = deletedAt;
  }


  public InvoiceDTO deletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    
    this.deletedBy = deletedBy;
    return this;
  }

  /**
   * Get deletedBy
   * @return deletedBy
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getDeletedBy() {
    return deletedBy;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    this.deletedBy = deletedBy;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InvoiceDTO invoiceDTO = (InvoiceDTO) o;
    return Objects.equals(this.id, invoiceDTO.id) &&
        Objects.equals(this.invoiceNo, invoiceDTO.invoiceNo) &&
        Objects.equals(this.issuedAt, invoiceDTO.issuedAt) &&
        Objects.equals(this.grossAmount, invoiceDTO.grossAmount) &&
        Objects.equals(this.vatAmount, invoiceDTO.vatAmount) &&
        Objects.equals(this.netAmount, invoiceDTO.netAmount) &&
        Objects.equals(this.createdAt, invoiceDTO.createdAt) &&
        Objects.equals(this.updatedAt, invoiceDTO.updatedAt) &&
        Objects.equals(this.isDeleted, invoiceDTO.isDeleted) &&
        Objects.equals(this.deletedAt, invoiceDTO.deletedAt) &&
        Objects.equals(this.deletedBy, invoiceDTO.deletedBy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, invoiceNo, issuedAt, grossAmount, vatAmount, netAmount, createdAt, updatedAt, isDeleted, deletedAt, deletedBy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InvoiceDTO {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    invoiceNo: ").append(toIndentedString(invoiceNo)).append("\n");
    sb.append("    issuedAt: ").append(toIndentedString(issuedAt)).append("\n");
    sb.append("    grossAmount: ").append(toIndentedString(grossAmount)).append("\n");
    sb.append("    vatAmount: ").append(toIndentedString(vatAmount)).append("\n");
    sb.append("    netAmount: ").append(toIndentedString(netAmount)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    deletedBy: ").append(toIndentedString(deletedBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

