/*
 * Ms Booking API
 * Ms Booking API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.msbooking.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ridehub.msbooking.client.model.BookingDTO;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TicketDTO
 */
@JsonPropertyOrder({
  TicketDTO.JSON_PROPERTY_ID,
  TicketDTO.JSON_PROPERTY_TICKET_CODE,
  TicketDTO.JSON_PROPERTY_PRICE,
  TicketDTO.JSON_PROPERTY_QR_CODE,
  TicketDTO.JSON_PROPERTY_TIME_FROM,
  TicketDTO.JSON_PROPERTY_TIME_TO,
  TicketDTO.JSON_PROPERTY_CHECKED_IN,
  TicketDTO.JSON_PROPERTY_TRIP_ID,
  TicketDTO.JSON_PROPERTY_ROUTE_ID,
  TicketDTO.JSON_PROPERTY_TRIP_SEAT_ID,
  TicketDTO.JSON_PROPERTY_CREATED_AT,
  TicketDTO.JSON_PROPERTY_UPDATED_AT,
  TicketDTO.JSON_PROPERTY_IS_DELETED,
  TicketDTO.JSON_PROPERTY_DELETED_AT,
  TicketDTO.JSON_PROPERTY_DELETED_BY,
  TicketDTO.JSON_PROPERTY_BOOKING
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class TicketDTO {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_TICKET_CODE = "ticketCode";
  @jakarta.annotation.Nonnull
  private String ticketCode;

  public static final String JSON_PROPERTY_PRICE = "price";
  @jakarta.annotation.Nonnull
  private BigDecimal price;

  public static final String JSON_PROPERTY_QR_CODE = "qrCode";
  @jakarta.annotation.Nullable
  private String qrCode;

  public static final String JSON_PROPERTY_TIME_FROM = "timeFrom";
  @jakarta.annotation.Nullable
  private OffsetDateTime timeFrom;

  public static final String JSON_PROPERTY_TIME_TO = "timeTo";
  @jakarta.annotation.Nullable
  private OffsetDateTime timeTo;

  public static final String JSON_PROPERTY_CHECKED_IN = "checkedIn";
  @jakarta.annotation.Nullable
  private Boolean checkedIn;

  public static final String JSON_PROPERTY_TRIP_ID = "tripId";
  @jakarta.annotation.Nonnull
  private UUID tripId;

  public static final String JSON_PROPERTY_ROUTE_ID = "routeId";
  @jakarta.annotation.Nonnull
  private UUID routeId;

  public static final String JSON_PROPERTY_TRIP_SEAT_ID = "tripSeatId";
  @jakarta.annotation.Nonnull
  private UUID tripSeatId;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  @jakarta.annotation.Nullable
  private Boolean isDeleted;

  public static final String JSON_PROPERTY_DELETED_AT = "deletedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime deletedAt;

  public static final String JSON_PROPERTY_DELETED_BY = "deletedBy";
  @jakarta.annotation.Nullable
  private UUID deletedBy;

  public static final String JSON_PROPERTY_BOOKING = "booking";
  @jakarta.annotation.Nonnull
  private BookingDTO booking;

  public TicketDTO() {
  }

  public TicketDTO id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }


  public TicketDTO ticketCode(@jakarta.annotation.Nonnull String ticketCode) {
    
    this.ticketCode = ticketCode;
    return this;
  }

  /**
   * Get ticketCode
   * @return ticketCode
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TICKET_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTicketCode() {
    return ticketCode;
  }


  @JsonProperty(JSON_PROPERTY_TICKET_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTicketCode(@jakarta.annotation.Nonnull String ticketCode) {
    this.ticketCode = ticketCode;
  }


  public TicketDTO price(@jakarta.annotation.Nonnull BigDecimal price) {
    
    this.price = price;
    return this;
  }

  /**
   * Get price
   * @return price
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BigDecimal getPrice() {
    return price;
  }


  @JsonProperty(JSON_PROPERTY_PRICE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPrice(@jakarta.annotation.Nonnull BigDecimal price) {
    this.price = price;
  }


  public TicketDTO qrCode(@jakarta.annotation.Nullable String qrCode) {
    
    this.qrCode = qrCode;
    return this;
  }

  /**
   * Get qrCode
   * @return qrCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QR_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getQrCode() {
    return qrCode;
  }


  @JsonProperty(JSON_PROPERTY_QR_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQrCode(@jakarta.annotation.Nullable String qrCode) {
    this.qrCode = qrCode;
  }


  public TicketDTO timeFrom(@jakarta.annotation.Nullable OffsetDateTime timeFrom) {
    
    this.timeFrom = timeFrom;
    return this;
  }

  /**
   * Get timeFrom
   * @return timeFrom
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIME_FROM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getTimeFrom() {
    return timeFrom;
  }


  @JsonProperty(JSON_PROPERTY_TIME_FROM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeFrom(@jakarta.annotation.Nullable OffsetDateTime timeFrom) {
    this.timeFrom = timeFrom;
  }


  public TicketDTO timeTo(@jakarta.annotation.Nullable OffsetDateTime timeTo) {
    
    this.timeTo = timeTo;
    return this;
  }

  /**
   * Get timeTo
   * @return timeTo
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TIME_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getTimeTo() {
    return timeTo;
  }


  @JsonProperty(JSON_PROPERTY_TIME_TO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTimeTo(@jakarta.annotation.Nullable OffsetDateTime timeTo) {
    this.timeTo = timeTo;
  }


  public TicketDTO checkedIn(@jakarta.annotation.Nullable Boolean checkedIn) {
    
    this.checkedIn = checkedIn;
    return this;
  }

  /**
   * Get checkedIn
   * @return checkedIn
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHECKED_IN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCheckedIn() {
    return checkedIn;
  }


  @JsonProperty(JSON_PROPERTY_CHECKED_IN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCheckedIn(@jakarta.annotation.Nullable Boolean checkedIn) {
    this.checkedIn = checkedIn;
  }


  public TicketDTO tripId(@jakarta.annotation.Nonnull UUID tripId) {
    
    this.tripId = tripId;
    return this;
  }

  /**
   * Get tripId
   * @return tripId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRIP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getTripId() {
    return tripId;
  }


  @JsonProperty(JSON_PROPERTY_TRIP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTripId(@jakarta.annotation.Nonnull UUID tripId) {
    this.tripId = tripId;
  }


  public TicketDTO routeId(@jakarta.annotation.Nonnull UUID routeId) {
    
    this.routeId = routeId;
    return this;
  }

  /**
   * Get routeId
   * @return routeId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ROUTE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getRouteId() {
    return routeId;
  }


  @JsonProperty(JSON_PROPERTY_ROUTE_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRouteId(@jakarta.annotation.Nonnull UUID routeId) {
    this.routeId = routeId;
  }


  public TicketDTO tripSeatId(@jakarta.annotation.Nonnull UUID tripSeatId) {
    
    this.tripSeatId = tripSeatId;
    return this;
  }

  /**
   * Get tripSeatId
   * @return tripSeatId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRIP_SEAT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public UUID getTripSeatId() {
    return tripSeatId;
  }


  @JsonProperty(JSON_PROPERTY_TRIP_SEAT_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTripSeatId(@jakarta.annotation.Nonnull UUID tripSeatId) {
    this.tripSeatId = tripSeatId;
  }


  public TicketDTO createdAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public TicketDTO updatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public TicketDTO isDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    
    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * Get isDeleted
   * @return isDeleted
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsDeleted() {
    return isDeleted;
  }


  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }


  public TicketDTO deletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    
    this.deletedAt = deletedAt;
    return this;
  }

  /**
   * Get deletedAt
   * @return deletedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDeletedAt() {
    return deletedAt;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    this.deletedAt = deletedAt;
  }


  public TicketDTO deletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    
    this.deletedBy = deletedBy;
    return this;
  }

  /**
   * Get deletedBy
   * @return deletedBy
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getDeletedBy() {
    return deletedBy;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    this.deletedBy = deletedBy;
  }


  public TicketDTO booking(@jakarta.annotation.Nonnull BookingDTO booking) {
    
    this.booking = booking;
    return this;
  }

  /**
   * Get booking
   * @return booking
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BOOKING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public BookingDTO getBooking() {
    return booking;
  }


  @JsonProperty(JSON_PROPERTY_BOOKING)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBooking(@jakarta.annotation.Nonnull BookingDTO booking) {
    this.booking = booking;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TicketDTO ticketDTO = (TicketDTO) o;
    return Objects.equals(this.id, ticketDTO.id) &&
        Objects.equals(this.ticketCode, ticketDTO.ticketCode) &&
        Objects.equals(this.price, ticketDTO.price) &&
        Objects.equals(this.qrCode, ticketDTO.qrCode) &&
        Objects.equals(this.timeFrom, ticketDTO.timeFrom) &&
        Objects.equals(this.timeTo, ticketDTO.timeTo) &&
        Objects.equals(this.checkedIn, ticketDTO.checkedIn) &&
        Objects.equals(this.tripId, ticketDTO.tripId) &&
        Objects.equals(this.routeId, ticketDTO.routeId) &&
        Objects.equals(this.tripSeatId, ticketDTO.tripSeatId) &&
        Objects.equals(this.createdAt, ticketDTO.createdAt) &&
        Objects.equals(this.updatedAt, ticketDTO.updatedAt) &&
        Objects.equals(this.isDeleted, ticketDTO.isDeleted) &&
        Objects.equals(this.deletedAt, ticketDTO.deletedAt) &&
        Objects.equals(this.deletedBy, ticketDTO.deletedBy) &&
        Objects.equals(this.booking, ticketDTO.booking);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, ticketCode, price, qrCode, timeFrom, timeTo, checkedIn, tripId, routeId, tripSeatId, createdAt, updatedAt, isDeleted, deletedAt, deletedBy, booking);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TicketDTO {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    ticketCode: ").append(toIndentedString(ticketCode)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    qrCode: ").append(toIndentedString(qrCode)).append("\n");
    sb.append("    timeFrom: ").append(toIndentedString(timeFrom)).append("\n");
    sb.append("    timeTo: ").append(toIndentedString(timeTo)).append("\n");
    sb.append("    checkedIn: ").append(toIndentedString(checkedIn)).append("\n");
    sb.append("    tripId: ").append(toIndentedString(tripId)).append("\n");
    sb.append("    routeId: ").append(toIndentedString(routeId)).append("\n");
    sb.append("    tripSeatId: ").append(toIndentedString(tripSeatId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    deletedBy: ").append(toIndentedString(deletedBy)).append("\n");
    sb.append("    booking: ").append(toIndentedString(booking)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

