/*
 * Ms Route API
 * Ms Route API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.msroute.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ridehub.msroute.client.model.SeatMapDTO;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * FloorDTO
 */
@JsonPropertyOrder({
  FloorDTO.JSON_PROPERTY_ID,
  FloorDTO.JSON_PROPERTY_FLOOR_NO,
  FloorDTO.JSON_PROPERTY_PRICE_FACTOR_FLOOR,
  FloorDTO.JSON_PROPERTY_CREATED_AT,
  FloorDTO.JSON_PROPERTY_UPDATED_AT,
  FloorDTO.JSON_PROPERTY_IS_DELETED,
  FloorDTO.JSON_PROPERTY_DELETED_AT,
  FloorDTO.JSON_PROPERTY_DELETED_BY,
  FloorDTO.JSON_PROPERTY_SEAT_MAP
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class FloorDTO {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_FLOOR_NO = "floorNo";
  @jakarta.annotation.Nonnull
  private Integer floorNo;

  public static final String JSON_PROPERTY_PRICE_FACTOR_FLOOR = "priceFactorFloor";
  @jakarta.annotation.Nullable
  private BigDecimal priceFactorFloor;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  @jakarta.annotation.Nullable
  private Boolean isDeleted;

  public static final String JSON_PROPERTY_DELETED_AT = "deletedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime deletedAt;

  public static final String JSON_PROPERTY_DELETED_BY = "deletedBy";
  @jakarta.annotation.Nullable
  private UUID deletedBy;

  public static final String JSON_PROPERTY_SEAT_MAP = "seatMap";
  @jakarta.annotation.Nonnull
  private SeatMapDTO seatMap;

  public FloorDTO() {
  }

  public FloorDTO id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }


  public FloorDTO floorNo(@jakarta.annotation.Nonnull Integer floorNo) {
    
    this.floorNo = floorNo;
    return this;
  }

  /**
   * Get floorNo
   * @return floorNo
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FLOOR_NO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getFloorNo() {
    return floorNo;
  }


  @JsonProperty(JSON_PROPERTY_FLOOR_NO)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFloorNo(@jakarta.annotation.Nonnull Integer floorNo) {
    this.floorNo = floorNo;
  }


  public FloorDTO priceFactorFloor(@jakarta.annotation.Nullable BigDecimal priceFactorFloor) {
    
    this.priceFactorFloor = priceFactorFloor;
    return this;
  }

  /**
   * Get priceFactorFloor
   * @return priceFactorFloor
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRICE_FACTOR_FLOOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public BigDecimal getPriceFactorFloor() {
    return priceFactorFloor;
  }


  @JsonProperty(JSON_PROPERTY_PRICE_FACTOR_FLOOR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPriceFactorFloor(@jakarta.annotation.Nullable BigDecimal priceFactorFloor) {
    this.priceFactorFloor = priceFactorFloor;
  }


  public FloorDTO createdAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public FloorDTO updatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public FloorDTO isDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    
    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * Get isDeleted
   * @return isDeleted
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsDeleted() {
    return isDeleted;
  }


  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }


  public FloorDTO deletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    
    this.deletedAt = deletedAt;
    return this;
  }

  /**
   * Get deletedAt
   * @return deletedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDeletedAt() {
    return deletedAt;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    this.deletedAt = deletedAt;
  }


  public FloorDTO deletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    
    this.deletedBy = deletedBy;
    return this;
  }

  /**
   * Get deletedBy
   * @return deletedBy
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getDeletedBy() {
    return deletedBy;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    this.deletedBy = deletedBy;
  }


  public FloorDTO seatMap(@jakarta.annotation.Nonnull SeatMapDTO seatMap) {
    
    this.seatMap = seatMap;
    return this;
  }

  /**
   * Get seatMap
   * @return seatMap
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_SEAT_MAP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public SeatMapDTO getSeatMap() {
    return seatMap;
  }


  @JsonProperty(JSON_PROPERTY_SEAT_MAP)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSeatMap(@jakarta.annotation.Nonnull SeatMapDTO seatMap) {
    this.seatMap = seatMap;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FloorDTO floorDTO = (FloorDTO) o;
    return Objects.equals(this.id, floorDTO.id) &&
        Objects.equals(this.floorNo, floorDTO.floorNo) &&
        Objects.equals(this.priceFactorFloor, floorDTO.priceFactorFloor) &&
        Objects.equals(this.createdAt, floorDTO.createdAt) &&
        Objects.equals(this.updatedAt, floorDTO.updatedAt) &&
        Objects.equals(this.isDeleted, floorDTO.isDeleted) &&
        Objects.equals(this.deletedAt, floorDTO.deletedAt) &&
        Objects.equals(this.deletedBy, floorDTO.deletedBy) &&
        Objects.equals(this.seatMap, floorDTO.seatMap);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, floorNo, priceFactorFloor, createdAt, updatedAt, isDeleted, deletedAt, deletedBy, seatMap);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FloorDTO {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    floorNo: ").append(toIndentedString(floorNo)).append("\n");
    sb.append("    priceFactorFloor: ").append(toIndentedString(priceFactorFloor)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    deletedBy: ").append(toIndentedString(deletedBy)).append("\n");
    sb.append("    seatMap: ").append(toIndentedString(seatMap)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

