/*
 * Ms Route API
 * Ms Route API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.msroute.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ProvinceDTO
 */
@JsonPropertyOrder({
  ProvinceDTO.JSON_PROPERTY_ID,
  ProvinceDTO.JSON_PROPERTY_PROVINCE_CODE,
  ProvinceDTO.JSON_PROPERTY_NAME,
  ProvinceDTO.JSON_PROPERTY_NAME_EN,
  ProvinceDTO.JSON_PROPERTY_FULL_NAME,
  ProvinceDTO.JSON_PROPERTY_FULL_NAME_EN,
  ProvinceDTO.JSON_PROPERTY_CODE_NAME,
  ProvinceDTO.JSON_PROPERTY_ADMINISTRATIVE_UNIT_ID,
  ProvinceDTO.JSON_PROPERTY_ADMINISTRATIVE_REGION_ID,
  ProvinceDTO.JSON_PROPERTY_CREATED_AT,
  ProvinceDTO.JSON_PROPERTY_UPDATED_AT,
  ProvinceDTO.JSON_PROPERTY_IS_DELETED,
  ProvinceDTO.JSON_PROPERTY_DELETED_AT,
  ProvinceDTO.JSON_PROPERTY_DELETED_BY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class ProvinceDTO {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_PROVINCE_CODE = "provinceCode";
  @jakarta.annotation.Nonnull
  private String provinceCode;

  public static final String JSON_PROPERTY_NAME = "name";
  @jakarta.annotation.Nonnull
  private String name;

  public static final String JSON_PROPERTY_NAME_EN = "nameEn";
  @jakarta.annotation.Nullable
  private String nameEn;

  public static final String JSON_PROPERTY_FULL_NAME = "fullName";
  @jakarta.annotation.Nullable
  private String fullName;

  public static final String JSON_PROPERTY_FULL_NAME_EN = "fullNameEn";
  @jakarta.annotation.Nullable
  private String fullNameEn;

  public static final String JSON_PROPERTY_CODE_NAME = "codeName";
  @jakarta.annotation.Nullable
  private String codeName;

  public static final String JSON_PROPERTY_ADMINISTRATIVE_UNIT_ID = "administrativeUnitId";
  @jakarta.annotation.Nullable
  private Integer administrativeUnitId;

  public static final String JSON_PROPERTY_ADMINISTRATIVE_REGION_ID = "administrativeRegionId";
  @jakarta.annotation.Nullable
  private Integer administrativeRegionId;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  @jakarta.annotation.Nullable
  private Boolean isDeleted;

  public static final String JSON_PROPERTY_DELETED_AT = "deletedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime deletedAt;

  public static final String JSON_PROPERTY_DELETED_BY = "deletedBy";
  @jakarta.annotation.Nullable
  private UUID deletedBy;

  public ProvinceDTO() {
  }

  public ProvinceDTO id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }


  public ProvinceDTO provinceCode(@jakarta.annotation.Nonnull String provinceCode) {
    
    this.provinceCode = provinceCode;
    return this;
  }

  /**
   * Get provinceCode
   * @return provinceCode
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_PROVINCE_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getProvinceCode() {
    return provinceCode;
  }


  @JsonProperty(JSON_PROPERTY_PROVINCE_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProvinceCode(@jakarta.annotation.Nonnull String provinceCode) {
    this.provinceCode = provinceCode;
  }


  public ProvinceDTO name(@jakarta.annotation.Nonnull String name) {
    
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getName() {
    return name;
  }


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setName(@jakarta.annotation.Nonnull String name) {
    this.name = name;
  }


  public ProvinceDTO nameEn(@jakarta.annotation.Nullable String nameEn) {
    
    this.nameEn = nameEn;
    return this;
  }

  /**
   * Get nameEn
   * @return nameEn
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME_EN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNameEn() {
    return nameEn;
  }


  @JsonProperty(JSON_PROPERTY_NAME_EN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNameEn(@jakarta.annotation.Nullable String nameEn) {
    this.nameEn = nameEn;
  }


  public ProvinceDTO fullName(@jakarta.annotation.Nullable String fullName) {
    
    this.fullName = fullName;
    return this;
  }

  /**
   * Get fullName
   * @return fullName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FULL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFullName() {
    return fullName;
  }


  @JsonProperty(JSON_PROPERTY_FULL_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFullName(@jakarta.annotation.Nullable String fullName) {
    this.fullName = fullName;
  }


  public ProvinceDTO fullNameEn(@jakarta.annotation.Nullable String fullNameEn) {
    
    this.fullNameEn = fullNameEn;
    return this;
  }

  /**
   * Get fullNameEn
   * @return fullNameEn
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FULL_NAME_EN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFullNameEn() {
    return fullNameEn;
  }


  @JsonProperty(JSON_PROPERTY_FULL_NAME_EN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFullNameEn(@jakarta.annotation.Nullable String fullNameEn) {
    this.fullNameEn = fullNameEn;
  }


  public ProvinceDTO codeName(@jakarta.annotation.Nullable String codeName) {
    
    this.codeName = codeName;
    return this;
  }

  /**
   * Get codeName
   * @return codeName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CODE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCodeName() {
    return codeName;
  }


  @JsonProperty(JSON_PROPERTY_CODE_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCodeName(@jakarta.annotation.Nullable String codeName) {
    this.codeName = codeName;
  }


  public ProvinceDTO administrativeUnitId(@jakarta.annotation.Nullable Integer administrativeUnitId) {
    
    this.administrativeUnitId = administrativeUnitId;
    return this;
  }

  /**
   * Get administrativeUnitId
   * @return administrativeUnitId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADMINISTRATIVE_UNIT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAdministrativeUnitId() {
    return administrativeUnitId;
  }


  @JsonProperty(JSON_PROPERTY_ADMINISTRATIVE_UNIT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdministrativeUnitId(@jakarta.annotation.Nullable Integer administrativeUnitId) {
    this.administrativeUnitId = administrativeUnitId;
  }


  public ProvinceDTO administrativeRegionId(@jakarta.annotation.Nullable Integer administrativeRegionId) {
    
    this.administrativeRegionId = administrativeRegionId;
    return this;
  }

  /**
   * Get administrativeRegionId
   * @return administrativeRegionId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADMINISTRATIVE_REGION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAdministrativeRegionId() {
    return administrativeRegionId;
  }


  @JsonProperty(JSON_PROPERTY_ADMINISTRATIVE_REGION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdministrativeRegionId(@jakarta.annotation.Nullable Integer administrativeRegionId) {
    this.administrativeRegionId = administrativeRegionId;
  }


  public ProvinceDTO createdAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public ProvinceDTO updatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public ProvinceDTO isDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    
    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * Get isDeleted
   * @return isDeleted
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsDeleted() {
    return isDeleted;
  }


  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }


  public ProvinceDTO deletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    
    this.deletedAt = deletedAt;
    return this;
  }

  /**
   * Get deletedAt
   * @return deletedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDeletedAt() {
    return deletedAt;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    this.deletedAt = deletedAt;
  }


  public ProvinceDTO deletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    
    this.deletedBy = deletedBy;
    return this;
  }

  /**
   * Get deletedBy
   * @return deletedBy
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getDeletedBy() {
    return deletedBy;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    this.deletedBy = deletedBy;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProvinceDTO provinceDTO = (ProvinceDTO) o;
    return Objects.equals(this.id, provinceDTO.id) &&
        Objects.equals(this.provinceCode, provinceDTO.provinceCode) &&
        Objects.equals(this.name, provinceDTO.name) &&
        Objects.equals(this.nameEn, provinceDTO.nameEn) &&
        Objects.equals(this.fullName, provinceDTO.fullName) &&
        Objects.equals(this.fullNameEn, provinceDTO.fullNameEn) &&
        Objects.equals(this.codeName, provinceDTO.codeName) &&
        Objects.equals(this.administrativeUnitId, provinceDTO.administrativeUnitId) &&
        Objects.equals(this.administrativeRegionId, provinceDTO.administrativeRegionId) &&
        Objects.equals(this.createdAt, provinceDTO.createdAt) &&
        Objects.equals(this.updatedAt, provinceDTO.updatedAt) &&
        Objects.equals(this.isDeleted, provinceDTO.isDeleted) &&
        Objects.equals(this.deletedAt, provinceDTO.deletedAt) &&
        Objects.equals(this.deletedBy, provinceDTO.deletedBy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, provinceCode, name, nameEn, fullName, fullNameEn, codeName, administrativeUnitId, administrativeRegionId, createdAt, updatedAt, isDeleted, deletedAt, deletedBy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProvinceDTO {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    provinceCode: ").append(toIndentedString(provinceCode)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    nameEn: ").append(toIndentedString(nameEn)).append("\n");
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    fullNameEn: ").append(toIndentedString(fullNameEn)).append("\n");
    sb.append("    codeName: ").append(toIndentedString(codeName)).append("\n");
    sb.append("    administrativeUnitId: ").append(toIndentedString(administrativeUnitId)).append("\n");
    sb.append("    administrativeRegionId: ").append(toIndentedString(administrativeRegionId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    deletedBy: ").append(toIndentedString(deletedBy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

