/*
 * Ms Route API
 * Ms Route API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.msroute.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SeatLockActionRequestDTO
 */
@JsonPropertyOrder({
  SeatLockActionRequestDTO.JSON_PROPERTY_BOOKING_ID,
  SeatLockActionRequestDTO.JSON_PROPERTY_TRIP_ID,
  SeatLockActionRequestDTO.JSON_PROPERTY_SEAT_NUMBERS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class SeatLockActionRequestDTO {
  public static final String JSON_PROPERTY_BOOKING_ID = "bookingId";
  @jakarta.annotation.Nonnull
  private Long bookingId;

  public static final String JSON_PROPERTY_TRIP_ID = "tripId";
  @jakarta.annotation.Nonnull
  private Long tripId;

  public static final String JSON_PROPERTY_SEAT_NUMBERS = "seatNumbers";
  @jakarta.annotation.Nullable
  private List<String> seatNumbers = new ArrayList<>();

  public SeatLockActionRequestDTO() {
  }

  public SeatLockActionRequestDTO bookingId(@jakarta.annotation.Nonnull Long bookingId) {
    
    this.bookingId = bookingId;
    return this;
  }

  /**
   * Get bookingId
   * @return bookingId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_BOOKING_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getBookingId() {
    return bookingId;
  }


  @JsonProperty(JSON_PROPERTY_BOOKING_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBookingId(@jakarta.annotation.Nonnull Long bookingId) {
    this.bookingId = bookingId;
  }


  public SeatLockActionRequestDTO tripId(@jakarta.annotation.Nonnull Long tripId) {
    
    this.tripId = tripId;
    return this;
  }

  /**
   * Get tripId
   * @return tripId
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TRIP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Long getTripId() {
    return tripId;
  }


  @JsonProperty(JSON_PROPERTY_TRIP_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTripId(@jakarta.annotation.Nonnull Long tripId) {
    this.tripId = tripId;
  }


  public SeatLockActionRequestDTO seatNumbers(@jakarta.annotation.Nullable List<String> seatNumbers) {
    
    this.seatNumbers = seatNumbers;
    return this;
  }

  public SeatLockActionRequestDTO addSeatNumbersItem(String seatNumbersItem) {
    if (this.seatNumbers == null) {
      this.seatNumbers = new ArrayList<>();
    }
    this.seatNumbers.add(seatNumbersItem);
    return this;
  }

  /**
   * Get seatNumbers
   * @return seatNumbers
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEAT_NUMBERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getSeatNumbers() {
    return seatNumbers;
  }


  @JsonProperty(JSON_PROPERTY_SEAT_NUMBERS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeatNumbers(@jakarta.annotation.Nullable List<String> seatNumbers) {
    this.seatNumbers = seatNumbers;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SeatLockActionRequestDTO seatLockActionRequestDTO = (SeatLockActionRequestDTO) o;
    return Objects.equals(this.bookingId, seatLockActionRequestDTO.bookingId) &&
        Objects.equals(this.tripId, seatLockActionRequestDTO.tripId) &&
        Objects.equals(this.seatNumbers, seatLockActionRequestDTO.seatNumbers);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bookingId, tripId, seatNumbers);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SeatLockActionRequestDTO {\n");
    sb.append("    bookingId: ").append(toIndentedString(bookingId)).append("\n");
    sb.append("    tripId: ").append(toIndentedString(tripId)).append("\n");
    sb.append("    seatNumbers: ").append(toIndentedString(seatNumbers)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

