/*
 * Ms Route API
 * Ms Route API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.msroute.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SeatLockResponseDTO
 */
@JsonPropertyOrder({
  SeatLockResponseDTO.JSON_PROPERTY_STATUS,
  SeatLockResponseDTO.JSON_PROPERTY_MESSAGE,
  SeatLockResponseDTO.JSON_PROPERTY_BOOKING_ID,
  SeatLockResponseDTO.JSON_PROPERTY_TRIP_ID,
  SeatLockResponseDTO.JSON_PROPERTY_LOCK_ID,
  SeatLockResponseDTO.JSON_PROPERTY_EXPIRES_AT
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class SeatLockResponseDTO {
  public static final String JSON_PROPERTY_STATUS = "status";
  @jakarta.annotation.Nullable
  private String status;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @jakarta.annotation.Nullable
  private String message;

  public static final String JSON_PROPERTY_BOOKING_ID = "bookingId";
  @jakarta.annotation.Nullable
  private Long bookingId;

  public static final String JSON_PROPERTY_TRIP_ID = "tripId";
  @jakarta.annotation.Nullable
  private Long tripId;

  public static final String JSON_PROPERTY_LOCK_ID = "lockId";
  @jakarta.annotation.Nullable
  private String lockId;

  public static final String JSON_PROPERTY_EXPIRES_AT = "expiresAt";
  @jakarta.annotation.Nullable
  private Long expiresAt;

  public SeatLockResponseDTO() {
  }

  public SeatLockResponseDTO status(@jakarta.annotation.Nullable String status) {
    
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getStatus() {
    return status;
  }


  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(@jakarta.annotation.Nullable String status) {
    this.status = status;
  }


  public SeatLockResponseDTO message(@jakarta.annotation.Nullable String message) {
    
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessage(@jakarta.annotation.Nullable String message) {
    this.message = message;
  }


  public SeatLockResponseDTO bookingId(@jakarta.annotation.Nullable Long bookingId) {
    
    this.bookingId = bookingId;
    return this;
  }

  /**
   * Get bookingId
   * @return bookingId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BOOKING_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getBookingId() {
    return bookingId;
  }


  @JsonProperty(JSON_PROPERTY_BOOKING_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBookingId(@jakarta.annotation.Nullable Long bookingId) {
    this.bookingId = bookingId;
  }


  public SeatLockResponseDTO tripId(@jakarta.annotation.Nullable Long tripId) {
    
    this.tripId = tripId;
    return this;
  }

  /**
   * Get tripId
   * @return tripId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRIP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTripId() {
    return tripId;
  }


  @JsonProperty(JSON_PROPERTY_TRIP_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTripId(@jakarta.annotation.Nullable Long tripId) {
    this.tripId = tripId;
  }


  public SeatLockResponseDTO lockId(@jakarta.annotation.Nullable String lockId) {
    
    this.lockId = lockId;
    return this;
  }

  /**
   * Get lockId
   * @return lockId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLockId() {
    return lockId;
  }


  @JsonProperty(JSON_PROPERTY_LOCK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLockId(@jakarta.annotation.Nullable String lockId) {
    this.lockId = lockId;
  }


  public SeatLockResponseDTO expiresAt(@jakarta.annotation.Nullable Long expiresAt) {
    
    this.expiresAt = expiresAt;
    return this;
  }

  /**
   * Get expiresAt
   * @return expiresAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPIRES_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getExpiresAt() {
    return expiresAt;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRES_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiresAt(@jakarta.annotation.Nullable Long expiresAt) {
    this.expiresAt = expiresAt;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SeatLockResponseDTO seatLockResponseDTO = (SeatLockResponseDTO) o;
    return Objects.equals(this.status, seatLockResponseDTO.status) &&
        Objects.equals(this.message, seatLockResponseDTO.message) &&
        Objects.equals(this.bookingId, seatLockResponseDTO.bookingId) &&
        Objects.equals(this.tripId, seatLockResponseDTO.tripId) &&
        Objects.equals(this.lockId, seatLockResponseDTO.lockId) &&
        Objects.equals(this.expiresAt, seatLockResponseDTO.expiresAt);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, message, bookingId, tripId, lockId, expiresAt);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SeatLockResponseDTO {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    bookingId: ").append(toIndentedString(bookingId)).append("\n");
    sb.append("    tripId: ").append(toIndentedString(tripId)).append("\n");
    sb.append("    lockId: ").append(toIndentedString(lockId)).append("\n");
    sb.append("    expiresAt: ").append(toIndentedString(expiresAt)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

