/*
 * Ms Route API
 * Ms Route API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.msroute.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ridehub.msroute.client.model.VehicleDTO;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * VehicleWithSeatCountVM
 */
@JsonPropertyOrder({
  VehicleWithSeatCountVM.JSON_PROPERTY_SEATS_COUNT,
  VehicleWithSeatCountVM.JSON_PROPERTY_VEHICLE_D_T_O
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class VehicleWithSeatCountVM {
  public static final String JSON_PROPERTY_SEATS_COUNT = "seatsCount";
  @jakarta.annotation.Nullable
  private Long seatsCount;

  public static final String JSON_PROPERTY_VEHICLE_D_T_O = "vehicleDTO";
  @jakarta.annotation.Nullable
  private VehicleDTO vehicleDTO;

  public VehicleWithSeatCountVM() {
  }

  public VehicleWithSeatCountVM seatsCount(@jakarta.annotation.Nullable Long seatsCount) {
    
    this.seatsCount = seatsCount;
    return this;
  }

  /**
   * Get seatsCount
   * @return seatsCount
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SEATS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getSeatsCount() {
    return seatsCount;
  }


  @JsonProperty(JSON_PROPERTY_SEATS_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSeatsCount(@jakarta.annotation.Nullable Long seatsCount) {
    this.seatsCount = seatsCount;
  }


  public VehicleWithSeatCountVM vehicleDTO(@jakarta.annotation.Nullable VehicleDTO vehicleDTO) {
    
    this.vehicleDTO = vehicleDTO;
    return this;
  }

  /**
   * Get vehicleDTO
   * @return vehicleDTO
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VEHICLE_D_T_O)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public VehicleDTO getVehicleDTO() {
    return vehicleDTO;
  }


  @JsonProperty(JSON_PROPERTY_VEHICLE_D_T_O)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVehicleDTO(@jakarta.annotation.Nullable VehicleDTO vehicleDTO) {
    this.vehicleDTO = vehicleDTO;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VehicleWithSeatCountVM vehicleWithSeatCountVM = (VehicleWithSeatCountVM) o;
    return Objects.equals(this.seatsCount, vehicleWithSeatCountVM.seatsCount) &&
        Objects.equals(this.vehicleDTO, vehicleWithSeatCountVM.vehicleDTO);
  }

  @Override
  public int hashCode() {
    return Objects.hash(seatsCount, vehicleDTO);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VehicleWithSeatCountVM {\n");
    sb.append("    seatsCount: ").append(toIndentedString(seatsCount)).append("\n");
    sb.append("    vehicleDTO: ").append(toIndentedString(vehicleDTO)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

