//// ===================================
//// ms_booking (Bookings, Tickets, Tx)
//// ===================================

Enum booking_status {
  DRAFT
  AWAITING_PAYMENT
  PAID
  CONFIRMED
  CANCELED
  REFUNDED
}

Enum payment_method {
  VNPAY
  MOMO
  ZALOPAY
  CREDIT_CARD
  BANK_TRANSFER
}

Enum payment_status {
  INITIATED
  PROCESSING
  SUCCESS
  FAILED
  REFUNDED
}

Table booking {
  id UUID [pk, not null]
  customer_id UUID [not null, note: 'AppUser.id from ms_user (logical)']
  booking_code varchar [not null, unique]
  status booking_status [not null]
  quantity int
  total_amount decimal(12,2) [not null]
  created_time timestamptz [not null]

  created_at timestamptz [not null]
  updated_at timestamptz
  is_deleted boolean
  deleted_at timestamptz
  deleted_by UUID
}

Table ticket {
  id UUID [pk, not null]
  booking_id UUID [not null, ref: > booking.id]
  trip_id UUID [not null, note: 'ms_route.trip.id (logical)']
  route_id UUID [not null, note: 'ms_route.route.id (logical)']
  trip_seat_id UUID [not null, note: 'ms_route.trip_seat.id (logical)']
  ticket_code varchar [not null, unique]
  price decimal(12,2) [not null]
  qr_code varchar
  time_from timestamptz
  time_to timestamptz
  checked_in boolean

  created_at timestamptz [not null]
  updated_at timestamptz
  is_deleted boolean
  deleted_at timestamptz
  deleted_by UUID

  Indexes {
    (trip_seat_id) [unique] // one ticket per seat instance
  }
}

Table payment_transaction {
  id UUID [pk, not null]
  booking_id UUID [not null, ref: > booking.id]
  transaction_id varchar [not null, unique]
  method payment_method
  status payment_status
  amount decimal(12,2)
  time timestamptz
  gateway_note text

  created_at timestamptz [not null]
  updated_at timestamptz
  is_deleted boolean
  deleted_at timestamptz
  deleted_by UUID
}

Table invoice {
  id UUID [pk, not null]
  booking_id UUID [not null, ref: > booking.id]
  invoice_no varchar [not null, unique]
  issued_at timestamptz
  gross_amount decimal(12,2)
  vat_amount decimal(12,2)
  net_amount decimal(12,2)

  created_at timestamptz [not null]
  updated_at timestamptz
  is_deleted boolean
  deleted_at timestamptz
  deleted_by UUID

  Indexes {
    (booking_id) [unique]
  }
}
