/*
 * Ms Promotion API
 * Ms Promotion API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.mspromotion.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ridehub.mspromotion.client.model.ConditionByLocationDTO;
import java.time.OffsetDateTime;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ConditionLocationItemDTO
 */
@JsonPropertyOrder({
  ConditionLocationItemDTO.JSON_PROPERTY_ID,
  ConditionLocationItemDTO.JSON_PROPERTY_PROVINCE_ID,
  ConditionLocationItemDTO.JSON_PROPERTY_DISTRICT_ID,
  ConditionLocationItemDTO.JSON_PROPERTY_WARD_ID,
  ConditionLocationItemDTO.JSON_PROPERTY_CREATED_AT,
  ConditionLocationItemDTO.JSON_PROPERTY_UPDATED_AT,
  ConditionLocationItemDTO.JSON_PROPERTY_IS_DELETED,
  ConditionLocationItemDTO.JSON_PROPERTY_DELETED_AT,
  ConditionLocationItemDTO.JSON_PROPERTY_DELETED_BY,
  ConditionLocationItemDTO.JSON_PROPERTY_CONDITION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class ConditionLocationItemDTO {
  public static final String JSON_PROPERTY_ID = "id";
  @jakarta.annotation.Nullable
  private Long id;

  public static final String JSON_PROPERTY_PROVINCE_ID = "provinceId";
  @jakarta.annotation.Nullable
  private Long provinceId;

  public static final String JSON_PROPERTY_DISTRICT_ID = "districtId";
  @jakarta.annotation.Nullable
  private Long districtId;

  public static final String JSON_PROPERTY_WARD_ID = "wardId";
  @jakarta.annotation.Nullable
  private Long wardId;

  public static final String JSON_PROPERTY_CREATED_AT = "createdAt";
  @jakarta.annotation.Nonnull
  private OffsetDateTime createdAt;

  public static final String JSON_PROPERTY_UPDATED_AT = "updatedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String JSON_PROPERTY_IS_DELETED = "isDeleted";
  @jakarta.annotation.Nullable
  private Boolean isDeleted;

  public static final String JSON_PROPERTY_DELETED_AT = "deletedAt";
  @jakarta.annotation.Nullable
  private OffsetDateTime deletedAt;

  public static final String JSON_PROPERTY_DELETED_BY = "deletedBy";
  @jakarta.annotation.Nullable
  private UUID deletedBy;

  public static final String JSON_PROPERTY_CONDITION = "condition";
  @jakarta.annotation.Nonnull
  private ConditionByLocationDTO condition;

  public ConditionLocationItemDTO() {
  }

  public ConditionLocationItemDTO id(@jakarta.annotation.Nullable Long id) {
    
    this.id = id;
    return this;
  }

  /**
   * Get id
   * @return id
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setId(@jakarta.annotation.Nullable Long id) {
    this.id = id;
  }


  public ConditionLocationItemDTO provinceId(@jakarta.annotation.Nullable Long provinceId) {
    
    this.provinceId = provinceId;
    return this;
  }

  /**
   * Get provinceId
   * @return provinceId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROVINCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getProvinceId() {
    return provinceId;
  }


  @JsonProperty(JSON_PROPERTY_PROVINCE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProvinceId(@jakarta.annotation.Nullable Long provinceId) {
    this.provinceId = provinceId;
  }


  public ConditionLocationItemDTO districtId(@jakarta.annotation.Nullable Long districtId) {
    
    this.districtId = districtId;
    return this;
  }

  /**
   * Get districtId
   * @return districtId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DISTRICT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getDistrictId() {
    return districtId;
  }


  @JsonProperty(JSON_PROPERTY_DISTRICT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDistrictId(@jakarta.annotation.Nullable Long districtId) {
    this.districtId = districtId;
  }


  public ConditionLocationItemDTO wardId(@jakarta.annotation.Nullable Long wardId) {
    
    this.wardId = wardId;
    return this;
  }

  /**
   * Get wardId
   * @return wardId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_WARD_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getWardId() {
    return wardId;
  }


  @JsonProperty(JSON_PROPERTY_WARD_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWardId(@jakarta.annotation.Nullable Long wardId) {
    this.wardId = wardId;
  }


  public ConditionLocationItemDTO createdAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

  /**
   * Get createdAt
   * @return createdAt
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  @JsonProperty(JSON_PROPERTY_CREATED_AT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCreatedAt(@jakarta.annotation.Nonnull OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public ConditionLocationItemDTO updatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    
    this.updatedAt = updatedAt;
    return this;
  }

  /**
   * Get updatedAt
   * @return updatedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  @JsonProperty(JSON_PROPERTY_UPDATED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdatedAt(@jakarta.annotation.Nullable OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }


  public ConditionLocationItemDTO isDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    
    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * Get isDeleted
   * @return isDeleted
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getIsDeleted() {
    return isDeleted;
  }


  @JsonProperty(JSON_PROPERTY_IS_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsDeleted(@jakarta.annotation.Nullable Boolean isDeleted) {
    this.isDeleted = isDeleted;
  }


  public ConditionLocationItemDTO deletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    
    this.deletedAt = deletedAt;
    return this;
  }

  /**
   * Get deletedAt
   * @return deletedAt
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getDeletedAt() {
    return deletedAt;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_AT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedAt(@jakarta.annotation.Nullable OffsetDateTime deletedAt) {
    this.deletedAt = deletedAt;
  }


  public ConditionLocationItemDTO deletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    
    this.deletedBy = deletedBy;
    return this;
  }

  /**
   * Get deletedBy
   * @return deletedBy
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getDeletedBy() {
    return deletedBy;
  }


  @JsonProperty(JSON_PROPERTY_DELETED_BY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDeletedBy(@jakarta.annotation.Nullable UUID deletedBy) {
    this.deletedBy = deletedBy;
  }


  public ConditionLocationItemDTO condition(@jakarta.annotation.Nonnull ConditionByLocationDTO condition) {
    
    this.condition = condition;
    return this;
  }

  /**
   * Get condition
   * @return condition
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CONDITION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ConditionByLocationDTO getCondition() {
    return condition;
  }


  @JsonProperty(JSON_PROPERTY_CONDITION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCondition(@jakarta.annotation.Nonnull ConditionByLocationDTO condition) {
    this.condition = condition;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConditionLocationItemDTO conditionLocationItemDTO = (ConditionLocationItemDTO) o;
    return Objects.equals(this.id, conditionLocationItemDTO.id) &&
        Objects.equals(this.provinceId, conditionLocationItemDTO.provinceId) &&
        Objects.equals(this.districtId, conditionLocationItemDTO.districtId) &&
        Objects.equals(this.wardId, conditionLocationItemDTO.wardId) &&
        Objects.equals(this.createdAt, conditionLocationItemDTO.createdAt) &&
        Objects.equals(this.updatedAt, conditionLocationItemDTO.updatedAt) &&
        Objects.equals(this.isDeleted, conditionLocationItemDTO.isDeleted) &&
        Objects.equals(this.deletedAt, conditionLocationItemDTO.deletedAt) &&
        Objects.equals(this.deletedBy, conditionLocationItemDTO.deletedBy) &&
        Objects.equals(this.condition, conditionLocationItemDTO.condition);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, provinceId, districtId, wardId, createdAt, updatedAt, isDeleted, deletedAt, deletedBy, condition);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConditionLocationItemDTO {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    provinceId: ").append(toIndentedString(provinceId)).append("\n");
    sb.append("    districtId: ").append(toIndentedString(districtId)).append("\n");
    sb.append("    wardId: ").append(toIndentedString(wardId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    isDeleted: ").append(toIndentedString(isDeleted)).append("\n");
    sb.append("    deletedAt: ").append(toIndentedString(deletedAt)).append("\n");
    sb.append("    deletedBy: ").append(toIndentedString(deletedBy)).append("\n");
    sb.append("    condition: ").append(toIndentedString(condition)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

