/*
 * Ms Promotion API
 * Ms Promotion API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.mspromotion.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ridehub.mspromotion.client.model.BuyNGetMFreeDTO;
import com.ridehub.mspromotion.client.model.ConditionByDateDTO;
import com.ridehub.mspromotion.client.model.ConditionByLocationDTO;
import com.ridehub.mspromotion.client.model.ConditionByRouteDTO;
import com.ridehub.mspromotion.client.model.PercentOffTotalDTO;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PromotionPoliciesAndConditionsDTO
 */
@JsonPropertyOrder({
  PromotionPoliciesAndConditionsDTO.JSON_PROPERTY_PROMOTION_ID,
  PromotionPoliciesAndConditionsDTO.JSON_PROPERTY_BUY_N_GET_M_FREE_POLICIES,
  PromotionPoliciesAndConditionsDTO.JSON_PROPERTY_PERCENT_OFF_TOTAL_POLICIES,
  PromotionPoliciesAndConditionsDTO.JSON_PROPERTY_DATE_CONDITIONS,
  PromotionPoliciesAndConditionsDTO.JSON_PROPERTY_ROUTE_CONDITIONS,
  PromotionPoliciesAndConditionsDTO.JSON_PROPERTY_LOCATION_CONDITIONS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class PromotionPoliciesAndConditionsDTO {
  public static final String JSON_PROPERTY_PROMOTION_ID = "promotionId";
  @jakarta.annotation.Nullable
  private Long promotionId;

  public static final String JSON_PROPERTY_BUY_N_GET_M_FREE_POLICIES = "buyNGetMFreePolicies";
  @jakarta.annotation.Nullable
  private List<BuyNGetMFreeDTO> buyNGetMFreePolicies = new ArrayList<>();

  public static final String JSON_PROPERTY_PERCENT_OFF_TOTAL_POLICIES = "percentOffTotalPolicies";
  @jakarta.annotation.Nullable
  private List<PercentOffTotalDTO> percentOffTotalPolicies = new ArrayList<>();

  public static final String JSON_PROPERTY_DATE_CONDITIONS = "dateConditions";
  @jakarta.annotation.Nullable
  private List<ConditionByDateDTO> dateConditions = new ArrayList<>();

  public static final String JSON_PROPERTY_ROUTE_CONDITIONS = "routeConditions";
  @jakarta.annotation.Nullable
  private List<ConditionByRouteDTO> routeConditions = new ArrayList<>();

  public static final String JSON_PROPERTY_LOCATION_CONDITIONS = "locationConditions";
  @jakarta.annotation.Nullable
  private List<ConditionByLocationDTO> locationConditions = new ArrayList<>();

  public PromotionPoliciesAndConditionsDTO() {
  }

  public PromotionPoliciesAndConditionsDTO promotionId(@jakarta.annotation.Nullable Long promotionId) {
    
    this.promotionId = promotionId;
    return this;
  }

  /**
   * Get promotionId
   * @return promotionId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROMOTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getPromotionId() {
    return promotionId;
  }


  @JsonProperty(JSON_PROPERTY_PROMOTION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPromotionId(@jakarta.annotation.Nullable Long promotionId) {
    this.promotionId = promotionId;
  }


  public PromotionPoliciesAndConditionsDTO buyNGetMFreePolicies(@jakarta.annotation.Nullable List<BuyNGetMFreeDTO> buyNGetMFreePolicies) {
    
    this.buyNGetMFreePolicies = buyNGetMFreePolicies;
    return this;
  }

  public PromotionPoliciesAndConditionsDTO addBuyNGetMFreePoliciesItem(BuyNGetMFreeDTO buyNGetMFreePoliciesItem) {
    if (this.buyNGetMFreePolicies == null) {
      this.buyNGetMFreePolicies = new ArrayList<>();
    }
    this.buyNGetMFreePolicies.add(buyNGetMFreePoliciesItem);
    return this;
  }

  /**
   * Get buyNGetMFreePolicies
   * @return buyNGetMFreePolicies
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUY_N_GET_M_FREE_POLICIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<BuyNGetMFreeDTO> getBuyNGetMFreePolicies() {
    return buyNGetMFreePolicies;
  }


  @JsonProperty(JSON_PROPERTY_BUY_N_GET_M_FREE_POLICIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBuyNGetMFreePolicies(@jakarta.annotation.Nullable List<BuyNGetMFreeDTO> buyNGetMFreePolicies) {
    this.buyNGetMFreePolicies = buyNGetMFreePolicies;
  }


  public PromotionPoliciesAndConditionsDTO percentOffTotalPolicies(@jakarta.annotation.Nullable List<PercentOffTotalDTO> percentOffTotalPolicies) {
    
    this.percentOffTotalPolicies = percentOffTotalPolicies;
    return this;
  }

  public PromotionPoliciesAndConditionsDTO addPercentOffTotalPoliciesItem(PercentOffTotalDTO percentOffTotalPoliciesItem) {
    if (this.percentOffTotalPolicies == null) {
      this.percentOffTotalPolicies = new ArrayList<>();
    }
    this.percentOffTotalPolicies.add(percentOffTotalPoliciesItem);
    return this;
  }

  /**
   * Get percentOffTotalPolicies
   * @return percentOffTotalPolicies
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PERCENT_OFF_TOTAL_POLICIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<PercentOffTotalDTO> getPercentOffTotalPolicies() {
    return percentOffTotalPolicies;
  }


  @JsonProperty(JSON_PROPERTY_PERCENT_OFF_TOTAL_POLICIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPercentOffTotalPolicies(@jakarta.annotation.Nullable List<PercentOffTotalDTO> percentOffTotalPolicies) {
    this.percentOffTotalPolicies = percentOffTotalPolicies;
  }


  public PromotionPoliciesAndConditionsDTO dateConditions(@jakarta.annotation.Nullable List<ConditionByDateDTO> dateConditions) {
    
    this.dateConditions = dateConditions;
    return this;
  }

  public PromotionPoliciesAndConditionsDTO addDateConditionsItem(ConditionByDateDTO dateConditionsItem) {
    if (this.dateConditions == null) {
      this.dateConditions = new ArrayList<>();
    }
    this.dateConditions.add(dateConditionsItem);
    return this;
  }

  /**
   * Get dateConditions
   * @return dateConditions
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATE_CONDITIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ConditionByDateDTO> getDateConditions() {
    return dateConditions;
  }


  @JsonProperty(JSON_PROPERTY_DATE_CONDITIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDateConditions(@jakarta.annotation.Nullable List<ConditionByDateDTO> dateConditions) {
    this.dateConditions = dateConditions;
  }


  public PromotionPoliciesAndConditionsDTO routeConditions(@jakarta.annotation.Nullable List<ConditionByRouteDTO> routeConditions) {
    
    this.routeConditions = routeConditions;
    return this;
  }

  public PromotionPoliciesAndConditionsDTO addRouteConditionsItem(ConditionByRouteDTO routeConditionsItem) {
    if (this.routeConditions == null) {
      this.routeConditions = new ArrayList<>();
    }
    this.routeConditions.add(routeConditionsItem);
    return this;
  }

  /**
   * Get routeConditions
   * @return routeConditions
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ROUTE_CONDITIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ConditionByRouteDTO> getRouteConditions() {
    return routeConditions;
  }


  @JsonProperty(JSON_PROPERTY_ROUTE_CONDITIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRouteConditions(@jakarta.annotation.Nullable List<ConditionByRouteDTO> routeConditions) {
    this.routeConditions = routeConditions;
  }


  public PromotionPoliciesAndConditionsDTO locationConditions(@jakarta.annotation.Nullable List<ConditionByLocationDTO> locationConditions) {
    
    this.locationConditions = locationConditions;
    return this;
  }

  public PromotionPoliciesAndConditionsDTO addLocationConditionsItem(ConditionByLocationDTO locationConditionsItem) {
    if (this.locationConditions == null) {
      this.locationConditions = new ArrayList<>();
    }
    this.locationConditions.add(locationConditionsItem);
    return this;
  }

  /**
   * Get locationConditions
   * @return locationConditions
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LOCATION_CONDITIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<ConditionByLocationDTO> getLocationConditions() {
    return locationConditions;
  }


  @JsonProperty(JSON_PROPERTY_LOCATION_CONDITIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLocationConditions(@jakarta.annotation.Nullable List<ConditionByLocationDTO> locationConditions) {
    this.locationConditions = locationConditions;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PromotionPoliciesAndConditionsDTO promotionPoliciesAndConditionsDTO = (PromotionPoliciesAndConditionsDTO) o;
    return Objects.equals(this.promotionId, promotionPoliciesAndConditionsDTO.promotionId) &&
        Objects.equals(this.buyNGetMFreePolicies, promotionPoliciesAndConditionsDTO.buyNGetMFreePolicies) &&
        Objects.equals(this.percentOffTotalPolicies, promotionPoliciesAndConditionsDTO.percentOffTotalPolicies) &&
        Objects.equals(this.dateConditions, promotionPoliciesAndConditionsDTO.dateConditions) &&
        Objects.equals(this.routeConditions, promotionPoliciesAndConditionsDTO.routeConditions) &&
        Objects.equals(this.locationConditions, promotionPoliciesAndConditionsDTO.locationConditions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(promotionId, buyNGetMFreePolicies, percentOffTotalPolicies, dateConditions, routeConditions, locationConditions);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PromotionPoliciesAndConditionsDTO {\n");
    sb.append("    promotionId: ").append(toIndentedString(promotionId)).append("\n");
    sb.append("    buyNGetMFreePolicies: ").append(toIndentedString(buyNGetMFreePolicies)).append("\n");
    sb.append("    percentOffTotalPolicies: ").append(toIndentedString(percentOffTotalPolicies)).append("\n");
    sb.append("    dateConditions: ").append(toIndentedString(dateConditions)).append("\n");
    sb.append("    routeConditions: ").append(toIndentedString(routeConditions)).append("\n");
    sb.append("    locationConditions: ").append(toIndentedString(locationConditions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

