/*
 * Ms User API
 * Ms User API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.msuser.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * AdminUpdatePasswordRequest
 */
@JsonPropertyOrder({
  AdminUpdatePasswordRequest.JSON_PROPERTY_NEW_PASSWORD,
  AdminUpdatePasswordRequest.JSON_PROPERTY_TEMPORARY
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class AdminUpdatePasswordRequest {
  public static final String JSON_PROPERTY_NEW_PASSWORD = "newPassword";
  @jakarta.annotation.Nullable
  private String newPassword;

  public static final String JSON_PROPERTY_TEMPORARY = "temporary";
  @jakarta.annotation.Nullable
  private Boolean temporary;

  public AdminUpdatePasswordRequest() {
  }

  public AdminUpdatePasswordRequest newPassword(@jakarta.annotation.Nullable String newPassword) {
    
    this.newPassword = newPassword;
    return this;
  }

  /**
   * Get newPassword
   * @return newPassword
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NEW_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNewPassword() {
    return newPassword;
  }


  @JsonProperty(JSON_PROPERTY_NEW_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNewPassword(@jakarta.annotation.Nullable String newPassword) {
    this.newPassword = newPassword;
  }


  public AdminUpdatePasswordRequest temporary(@jakarta.annotation.Nullable Boolean temporary) {
    
    this.temporary = temporary;
    return this;
  }

  /**
   * Get temporary
   * @return temporary
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TEMPORARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getTemporary() {
    return temporary;
  }


  @JsonProperty(JSON_PROPERTY_TEMPORARY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTemporary(@jakarta.annotation.Nullable Boolean temporary) {
    this.temporary = temporary;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AdminUpdatePasswordRequest adminUpdatePasswordRequest = (AdminUpdatePasswordRequest) o;
    return Objects.equals(this.newPassword, adminUpdatePasswordRequest.newPassword) &&
        Objects.equals(this.temporary, adminUpdatePasswordRequest.temporary);
  }

  @Override
  public int hashCode() {
    return Objects.hash(newPassword, temporary);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AdminUpdatePasswordRequest {\n");
    sb.append("    newPassword: ").append(toIndentedString(newPassword)).append("\n");
    sb.append("    temporary: ").append(toIndentedString(temporary)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

