/*
 * Ms User API
 * Ms User API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.msuser.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * PasswordResetRequestDTO
 */
@JsonPropertyOrder({
  PasswordResetRequestDTO.JSON_PROPERTY_RESET_TOKEN,
  PasswordResetRequestDTO.JSON_PROPERTY_NEW_PASSWORD
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class PasswordResetRequestDTO {
  public static final String JSON_PROPERTY_RESET_TOKEN = "resetToken";
  @jakarta.annotation.Nullable
  private String resetToken;

  public static final String JSON_PROPERTY_NEW_PASSWORD = "newPassword";
  @jakarta.annotation.Nullable
  private String newPassword;

  public PasswordResetRequestDTO() {
  }

  public PasswordResetRequestDTO resetToken(@jakarta.annotation.Nullable String resetToken) {
    
    this.resetToken = resetToken;
    return this;
  }

  /**
   * Get resetToken
   * @return resetToken
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RESET_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getResetToken() {
    return resetToken;
  }


  @JsonProperty(JSON_PROPERTY_RESET_TOKEN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setResetToken(@jakarta.annotation.Nullable String resetToken) {
    this.resetToken = resetToken;
  }


  public PasswordResetRequestDTO newPassword(@jakarta.annotation.Nullable String newPassword) {
    
    this.newPassword = newPassword;
    return this;
  }

  /**
   * Get newPassword
   * @return newPassword
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NEW_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getNewPassword() {
    return newPassword;
  }


  @JsonProperty(JSON_PROPERTY_NEW_PASSWORD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNewPassword(@jakarta.annotation.Nullable String newPassword) {
    this.newPassword = newPassword;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PasswordResetRequestDTO passwordResetRequestDTO = (PasswordResetRequestDTO) o;
    return Objects.equals(this.resetToken, passwordResetRequestDTO.resetToken) &&
        Objects.equals(this.newPassword, passwordResetRequestDTO.newPassword);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resetToken, newPassword);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PasswordResetRequestDTO {\n");
    sb.append("    resetToken: ").append(toIndentedString(resetToken)).append("\n");
    sb.append("    newPassword: ").append(toIndentedString(newPassword)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

