/*
 * Ms User API
 * Ms User API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.msuser.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * RegistrationCompleteResponseDTO
 */
@JsonPropertyOrder({
  RegistrationCompleteResponseDTO.JSON_PROPERTY_USER_ID,
  RegistrationCompleteResponseDTO.JSON_PROPERTY_KEYCLOAK_ID,
  RegistrationCompleteResponseDTO.JSON_PROPERTY_MESSAGE,
  RegistrationCompleteResponseDTO.JSON_PROPERTY_SUCCESS,
  RegistrationCompleteResponseDTO.JSON_PROPERTY_ERROR_CODE,
  RegistrationCompleteResponseDTO.JSON_PROPERTY_ERROR_DESCRIPTION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class RegistrationCompleteResponseDTO {
  public static final String JSON_PROPERTY_USER_ID = "userId";
  @jakarta.annotation.Nullable
  private String userId;

  public static final String JSON_PROPERTY_KEYCLOAK_ID = "keycloakId";
  @jakarta.annotation.Nullable
  private String keycloakId;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @jakarta.annotation.Nullable
  private String message;

  public static final String JSON_PROPERTY_SUCCESS = "success";
  @jakarta.annotation.Nullable
  private Boolean success;

  public static final String JSON_PROPERTY_ERROR_CODE = "errorCode";
  @jakarta.annotation.Nullable
  private String errorCode;

  public static final String JSON_PROPERTY_ERROR_DESCRIPTION = "errorDescription";
  @jakarta.annotation.Nullable
  private String errorDescription;

  public RegistrationCompleteResponseDTO() {
  }

  public RegistrationCompleteResponseDTO userId(@jakarta.annotation.Nullable String userId) {
    
    this.userId = userId;
    return this;
  }

  /**
   * Get userId
   * @return userId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUserId() {
    return userId;
  }


  @JsonProperty(JSON_PROPERTY_USER_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUserId(@jakarta.annotation.Nullable String userId) {
    this.userId = userId;
  }


  public RegistrationCompleteResponseDTO keycloakId(@jakarta.annotation.Nullable String keycloakId) {
    
    this.keycloakId = keycloakId;
    return this;
  }

  /**
   * Get keycloakId
   * @return keycloakId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KEYCLOAK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getKeycloakId() {
    return keycloakId;
  }


  @JsonProperty(JSON_PROPERTY_KEYCLOAK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKeycloakId(@jakarta.annotation.Nullable String keycloakId) {
    this.keycloakId = keycloakId;
  }


  public RegistrationCompleteResponseDTO message(@jakarta.annotation.Nullable String message) {
    
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessage(@jakarta.annotation.Nullable String message) {
    this.message = message;
  }


  public RegistrationCompleteResponseDTO success(@jakarta.annotation.Nullable Boolean success) {
    
    this.success = success;
    return this;
  }

  /**
   * Get success
   * @return success
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUCCESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getSuccess() {
    return success;
  }


  @JsonProperty(JSON_PROPERTY_SUCCESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSuccess(@jakarta.annotation.Nullable Boolean success) {
    this.success = success;
  }


  public RegistrationCompleteResponseDTO errorCode(@jakarta.annotation.Nullable String errorCode) {
    
    this.errorCode = errorCode;
    return this;
  }

  /**
   * Get errorCode
   * @return errorCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERROR_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getErrorCode() {
    return errorCode;
  }


  @JsonProperty(JSON_PROPERTY_ERROR_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrorCode(@jakarta.annotation.Nullable String errorCode) {
    this.errorCode = errorCode;
  }


  public RegistrationCompleteResponseDTO errorDescription(@jakarta.annotation.Nullable String errorDescription) {
    
    this.errorDescription = errorDescription;
    return this;
  }

  /**
   * Get errorDescription
   * @return errorDescription
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERROR_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getErrorDescription() {
    return errorDescription;
  }


  @JsonProperty(JSON_PROPERTY_ERROR_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrorDescription(@jakarta.annotation.Nullable String errorDescription) {
    this.errorDescription = errorDescription;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RegistrationCompleteResponseDTO registrationCompleteResponseDTO = (RegistrationCompleteResponseDTO) o;
    return Objects.equals(this.userId, registrationCompleteResponseDTO.userId) &&
        Objects.equals(this.keycloakId, registrationCompleteResponseDTO.keycloakId) &&
        Objects.equals(this.message, registrationCompleteResponseDTO.message) &&
        Objects.equals(this.success, registrationCompleteResponseDTO.success) &&
        Objects.equals(this.errorCode, registrationCompleteResponseDTO.errorCode) &&
        Objects.equals(this.errorDescription, registrationCompleteResponseDTO.errorDescription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, keycloakId, message, success, errorCode, errorDescription);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RegistrationCompleteResponseDTO {\n");
    sb.append("    userId: ").append(toIndentedString(userId)).append("\n");
    sb.append("    keycloakId: ").append(toIndentedString(keycloakId)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    errorDescription: ").append(toIndentedString(errorDescription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

