/*
 * Ms User API
 * Ms User API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.msuser.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SendOtpResponseDTO
 */
@JsonPropertyOrder({
  SendOtpResponseDTO.JSON_PROPERTY_TXN_ID,
  SendOtpResponseDTO.JSON_PROPERTY_EXPIRES_IN,
  SendOtpResponseDTO.JSON_PROPERTY_MESSAGE,
  SendOtpResponseDTO.JSON_PROPERTY_ERROR_CODE,
  SendOtpResponseDTO.JSON_PROPERTY_ERROR_DESCRIPTION
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class SendOtpResponseDTO {
  public static final String JSON_PROPERTY_TXN_ID = "txnId";
  @jakarta.annotation.Nullable
  private String txnId;

  public static final String JSON_PROPERTY_EXPIRES_IN = "expiresIn";
  @jakarta.annotation.Nullable
  private Long expiresIn;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  @jakarta.annotation.Nullable
  private String message;

  public static final String JSON_PROPERTY_ERROR_CODE = "errorCode";
  @jakarta.annotation.Nullable
  private String errorCode;

  public static final String JSON_PROPERTY_ERROR_DESCRIPTION = "errorDescription";
  @jakarta.annotation.Nullable
  private String errorDescription;

  public SendOtpResponseDTO() {
  }

  public SendOtpResponseDTO txnId(@jakarta.annotation.Nullable String txnId) {
    
    this.txnId = txnId;
    return this;
  }

  /**
   * Get txnId
   * @return txnId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TXN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTxnId() {
    return txnId;
  }


  @JsonProperty(JSON_PROPERTY_TXN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTxnId(@jakarta.annotation.Nullable String txnId) {
    this.txnId = txnId;
  }


  public SendOtpResponseDTO expiresIn(@jakarta.annotation.Nullable Long expiresIn) {
    
    this.expiresIn = expiresIn;
    return this;
  }

  /**
   * Get expiresIn
   * @return expiresIn
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXPIRES_IN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getExpiresIn() {
    return expiresIn;
  }


  @JsonProperty(JSON_PROPERTY_EXPIRES_IN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExpiresIn(@jakarta.annotation.Nullable Long expiresIn) {
    this.expiresIn = expiresIn;
  }


  public SendOtpResponseDTO message(@jakarta.annotation.Nullable String message) {
    
    this.message = message;
    return this;
  }

  /**
   * Get message
   * @return message
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessage() {
    return message;
  }


  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMessage(@jakarta.annotation.Nullable String message) {
    this.message = message;
  }


  public SendOtpResponseDTO errorCode(@jakarta.annotation.Nullable String errorCode) {
    
    this.errorCode = errorCode;
    return this;
  }

  /**
   * Get errorCode
   * @return errorCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERROR_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getErrorCode() {
    return errorCode;
  }


  @JsonProperty(JSON_PROPERTY_ERROR_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrorCode(@jakarta.annotation.Nullable String errorCode) {
    this.errorCode = errorCode;
  }


  public SendOtpResponseDTO errorDescription(@jakarta.annotation.Nullable String errorDescription) {
    
    this.errorDescription = errorDescription;
    return this;
  }

  /**
   * Get errorDescription
   * @return errorDescription
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERROR_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getErrorDescription() {
    return errorDescription;
  }


  @JsonProperty(JSON_PROPERTY_ERROR_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrorDescription(@jakarta.annotation.Nullable String errorDescription) {
    this.errorDescription = errorDescription;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SendOtpResponseDTO sendOtpResponseDTO = (SendOtpResponseDTO) o;
    return Objects.equals(this.txnId, sendOtpResponseDTO.txnId) &&
        Objects.equals(this.expiresIn, sendOtpResponseDTO.expiresIn) &&
        Objects.equals(this.message, sendOtpResponseDTO.message) &&
        Objects.equals(this.errorCode, sendOtpResponseDTO.errorCode) &&
        Objects.equals(this.errorDescription, sendOtpResponseDTO.errorDescription);
  }

  @Override
  public int hashCode() {
    return Objects.hash(txnId, expiresIn, message, errorCode, errorDescription);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SendOtpResponseDTO {\n");
    sb.append("    txnId: ").append(toIndentedString(txnId)).append("\n");
    sb.append("    expiresIn: ").append(toIndentedString(expiresIn)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    errorDescription: ").append(toIndentedString(errorDescription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

