/*
 * Ms User API
 * Ms User API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ridehub.msuser.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * UserInfoDTO
 */
@JsonPropertyOrder({
  UserInfoDTO.JSON_PROPERTY_KEYCLOAK_ID,
  UserInfoDTO.JSON_PROPERTY_USERNAME,
  UserInfoDTO.JSON_PROPERTY_EMAIL,
  UserInfoDTO.JSON_PROPERTY_FIRST_NAME,
  UserInfoDTO.JSON_PROPERTY_LAST_NAME,
  UserInfoDTO.JSON_PROPERTY_PHONE_NUMBER,
  UserInfoDTO.JSON_PROPERTY_EMAIL_VERIFIED,
  UserInfoDTO.JSON_PROPERTY_PHONE_VERIFIED,
  UserInfoDTO.JSON_PROPERTY_LAST_LOGIN
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.14.0")
public class UserInfoDTO {
  public static final String JSON_PROPERTY_KEYCLOAK_ID = "keycloakId";
  @jakarta.annotation.Nullable
  private String keycloakId;

  public static final String JSON_PROPERTY_USERNAME = "username";
  @jakarta.annotation.Nullable
  private String username;

  public static final String JSON_PROPERTY_EMAIL = "email";
  @jakarta.annotation.Nullable
  private String email;

  public static final String JSON_PROPERTY_FIRST_NAME = "firstName";
  @jakarta.annotation.Nullable
  private String firstName;

  public static final String JSON_PROPERTY_LAST_NAME = "lastName";
  @jakarta.annotation.Nullable
  private String lastName;

  public static final String JSON_PROPERTY_PHONE_NUMBER = "phoneNumber";
  @jakarta.annotation.Nullable
  private String phoneNumber;

  public static final String JSON_PROPERTY_EMAIL_VERIFIED = "emailVerified";
  @jakarta.annotation.Nullable
  private Boolean emailVerified;

  public static final String JSON_PROPERTY_PHONE_VERIFIED = "phoneVerified";
  @jakarta.annotation.Nullable
  private Boolean phoneVerified;

  public static final String JSON_PROPERTY_LAST_LOGIN = "lastLogin";
  @jakarta.annotation.Nullable
  private OffsetDateTime lastLogin;

  public UserInfoDTO() {
  }

  public UserInfoDTO keycloakId(@jakarta.annotation.Nullable String keycloakId) {
    
    this.keycloakId = keycloakId;
    return this;
  }

  /**
   * Get keycloakId
   * @return keycloakId
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_KEYCLOAK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getKeycloakId() {
    return keycloakId;
  }


  @JsonProperty(JSON_PROPERTY_KEYCLOAK_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setKeycloakId(@jakarta.annotation.Nullable String keycloakId) {
    this.keycloakId = keycloakId;
  }


  public UserInfoDTO username(@jakarta.annotation.Nullable String username) {
    
    this.username = username;
    return this;
  }

  /**
   * Get username
   * @return username
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUsername() {
    return username;
  }


  @JsonProperty(JSON_PROPERTY_USERNAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUsername(@jakarta.annotation.Nullable String username) {
    this.username = username;
  }


  public UserInfoDTO email(@jakarta.annotation.Nullable String email) {
    
    this.email = email;
    return this;
  }

  /**
   * Get email
   * @return email
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getEmail() {
    return email;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmail(@jakarta.annotation.Nullable String email) {
    this.email = email;
  }


  public UserInfoDTO firstName(@jakarta.annotation.Nullable String firstName) {
    
    this.firstName = firstName;
    return this;
  }

  /**
   * Get firstName
   * @return firstName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_FIRST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getFirstName() {
    return firstName;
  }


  @JsonProperty(JSON_PROPERTY_FIRST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFirstName(@jakarta.annotation.Nullable String firstName) {
    this.firstName = firstName;
  }


  public UserInfoDTO lastName(@jakarta.annotation.Nullable String lastName) {
    
    this.lastName = lastName;
    return this;
  }

  /**
   * Get lastName
   * @return lastName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getLastName() {
    return lastName;
  }


  @JsonProperty(JSON_PROPERTY_LAST_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastName(@jakarta.annotation.Nullable String lastName) {
    this.lastName = lastName;
  }


  public UserInfoDTO phoneNumber(@jakarta.annotation.Nullable String phoneNumber) {
    
    this.phoneNumber = phoneNumber;
    return this;
  }

  /**
   * Get phoneNumber
   * @return phoneNumber
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PHONE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPhoneNumber() {
    return phoneNumber;
  }


  @JsonProperty(JSON_PROPERTY_PHONE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhoneNumber(@jakarta.annotation.Nullable String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }


  public UserInfoDTO emailVerified(@jakarta.annotation.Nullable Boolean emailVerified) {
    
    this.emailVerified = emailVerified;
    return this;
  }

  /**
   * Get emailVerified
   * @return emailVerified
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EMAIL_VERIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getEmailVerified() {
    return emailVerified;
  }


  @JsonProperty(JSON_PROPERTY_EMAIL_VERIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEmailVerified(@jakarta.annotation.Nullable Boolean emailVerified) {
    this.emailVerified = emailVerified;
  }


  public UserInfoDTO phoneVerified(@jakarta.annotation.Nullable Boolean phoneVerified) {
    
    this.phoneVerified = phoneVerified;
    return this;
  }

  /**
   * Get phoneVerified
   * @return phoneVerified
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PHONE_VERIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPhoneVerified() {
    return phoneVerified;
  }


  @JsonProperty(JSON_PROPERTY_PHONE_VERIFIED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhoneVerified(@jakarta.annotation.Nullable Boolean phoneVerified) {
    this.phoneVerified = phoneVerified;
  }


  public UserInfoDTO lastLogin(@jakarta.annotation.Nullable OffsetDateTime lastLogin) {
    
    this.lastLogin = lastLogin;
    return this;
  }

  /**
   * Get lastLogin
   * @return lastLogin
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_LAST_LOGIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getLastLogin() {
    return lastLogin;
  }


  @JsonProperty(JSON_PROPERTY_LAST_LOGIN)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setLastLogin(@jakarta.annotation.Nullable OffsetDateTime lastLogin) {
    this.lastLogin = lastLogin;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserInfoDTO userInfoDTO = (UserInfoDTO) o;
    return Objects.equals(this.keycloakId, userInfoDTO.keycloakId) &&
        Objects.equals(this.username, userInfoDTO.username) &&
        Objects.equals(this.email, userInfoDTO.email) &&
        Objects.equals(this.firstName, userInfoDTO.firstName) &&
        Objects.equals(this.lastName, userInfoDTO.lastName) &&
        Objects.equals(this.phoneNumber, userInfoDTO.phoneNumber) &&
        Objects.equals(this.emailVerified, userInfoDTO.emailVerified) &&
        Objects.equals(this.phoneVerified, userInfoDTO.phoneVerified) &&
        Objects.equals(this.lastLogin, userInfoDTO.lastLogin);
  }

  @Override
  public int hashCode() {
    return Objects.hash(keycloakId, username, email, firstName, lastName, phoneNumber, emailVerified, phoneVerified, lastLogin);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserInfoDTO {\n");
    sb.append("    keycloakId: ").append(toIndentedString(keycloakId)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    phoneNumber: ").append(toIndentedString(phoneNumber)).append("\n");
    sb.append("    emailVerified: ").append(toIndentedString(emailVerified)).append("\n");
    sb.append("    phoneVerified: ").append(toIndentedString(phoneVerified)).append("\n");
    sb.append("    lastLogin: ").append(toIndentedString(lastLogin)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

