package com.ridehub.user.domain;

import static com.ridehub.user.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class TripRecommendationAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripRecommendationAllPropertiesEquals(TripRecommendation expected, TripRecommendation actual) {
        assertTripRecommendationAutoGeneratedPropertiesEquals(expected, actual);
        assertTripRecommendationAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripRecommendationAllUpdatablePropertiesEquals(TripRecommendation expected, TripRecommendation actual) {
        assertTripRecommendationUpdatableFieldsEquals(expected, actual);
        assertTripRecommendationUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripRecommendationAutoGeneratedPropertiesEquals(TripRecommendation expected, TripRecommendation actual) {
        assertThat(actual)
            .as("Verify TripRecommendation auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripRecommendationUpdatableFieldsEquals(TripRecommendation expected, TripRecommendation actual) {
        assertThat(actual)
            .as("Verify TripRecommendation relevant properties")
            .satisfies(a -> assertThat(a.getOrigin()).as("check origin").isEqualTo(expected.getOrigin()))
            .satisfies(a -> assertThat(a.getDestination()).as("check destination").isEqualTo(expected.getDestination()))
            .satisfies(a -> assertThat(a.getTravelDate()).as("check travelDate").isEqualTo(expected.getTravelDate()))
            .satisfies(a -> assertThat(a.getPreferredTime()).as("check preferredTime").isEqualTo(expected.getPreferredTime()))
            .satisfies(a -> assertThat(a.getBudgetRange()).as("check budgetRange").isEqualTo(expected.getBudgetRange()))
            .satisfies(a -> assertThat(a.getSeatPreference()).as("check seatPreference").isEqualTo(expected.getSeatPreference()))
            .satisfies(a -> assertThat(a.getRecommendedTrips()).as("check recommendedTrips").isEqualTo(expected.getRecommendedTrips()))
            .satisfies(a ->
                assertThat(a.getConfidenceScore())
                    .as("check confidenceScore")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getConfidenceScore())
            )
            .satisfies(a -> assertThat(a.getIsBooked()).as("check isBooked").isEqualTo(expected.getIsBooked()))
            .satisfies(a -> assertThat(a.getFeedbackRating()).as("check feedbackRating").isEqualTo(expected.getFeedbackRating()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()))
            .satisfies(a -> assertThat(a.getIsDeleted()).as("check isDeleted").isEqualTo(expected.getIsDeleted()))
            .satisfies(a -> assertThat(a.getDeletedAt()).as("check deletedAt").isEqualTo(expected.getDeletedAt()))
            .satisfies(a -> assertThat(a.getDeletedBy()).as("check deletedBy").isEqualTo(expected.getDeletedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripRecommendationUpdatableRelationshipsEquals(TripRecommendation expected, TripRecommendation actual) {
        assertThat(actual)
            .as("Verify TripRecommendation relationships")
            .satisfies(a -> assertThat(a.getUser()).as("check user").isEqualTo(expected.getUser()));
    }
}
