package com.ridehub.user.domain;

import static com.ridehub.user.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class TripStatisticsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripStatisticsAllPropertiesEquals(TripStatistics expected, TripStatistics actual) {
        assertTripStatisticsAutoGeneratedPropertiesEquals(expected, actual);
        assertTripStatisticsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripStatisticsAllUpdatablePropertiesEquals(TripStatistics expected, TripStatistics actual) {
        assertTripStatisticsUpdatableFieldsEquals(expected, actual);
        assertTripStatisticsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripStatisticsAutoGeneratedPropertiesEquals(TripStatistics expected, TripStatistics actual) {
        assertThat(actual)
            .as("Verify TripStatistics auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripStatisticsUpdatableFieldsEquals(TripStatistics expected, TripStatistics actual) {
        assertThat(actual)
            .as("Verify TripStatistics relevant properties")
            .satisfies(a -> assertThat(a.getRouteId()).as("check routeId").isEqualTo(expected.getRouteId()))
            .satisfies(a -> assertThat(a.getVehicleType()).as("check vehicleType").isEqualTo(expected.getVehicleType()))
            .satisfies(a -> assertThat(a.getOccasionType()).as("check occasionType").isEqualTo(expected.getOccasionType()))
            .satisfies(a -> assertThat(a.getTotalBookings()).as("check totalBookings").isEqualTo(expected.getTotalBookings()))
            .satisfies(a ->
                assertThat(a.getTotalRevenue())
                    .as("check totalRevenue")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalRevenue())
            )
            .satisfies(a ->
                assertThat(a.getAveragePrice())
                    .as("check averagePrice")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getAveragePrice())
            )
            .satisfies(a ->
                assertThat(a.getOccupancyRate())
                    .as("check occupancyRate")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getOccupancyRate())
            )
            .satisfies(a -> assertThat(a.getPopularSeatTypes()).as("check popularSeatTypes").isEqualTo(expected.getPopularSeatTypes()))
            .satisfies(a -> assertThat(a.getPeakTravelTimes()).as("check peakTravelTimes").isEqualTo(expected.getPeakTravelTimes()))
            .satisfies(a ->
                assertThat(a.getCancellationRate())
                    .as("check cancellationRate")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCancellationRate())
            )
            .satisfies(a ->
                assertThat(a.getCustomerSatisfactionScore())
                    .as("check customerSatisfactionScore")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getCustomerSatisfactionScore())
            )
            .satisfies(a -> assertThat(a.getMonthlyTrend()).as("check monthlyTrend").isEqualTo(expected.getMonthlyTrend()))
            .satisfies(a -> assertThat(a.getValidFrom()).as("check validFrom").isEqualTo(expected.getValidFrom()))
            .satisfies(a -> assertThat(a.getValidTo()).as("check validTo").isEqualTo(expected.getValidTo()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()))
            .satisfies(a -> assertThat(a.getIsDeleted()).as("check isDeleted").isEqualTo(expected.getIsDeleted()))
            .satisfies(a -> assertThat(a.getDeletedAt()).as("check deletedAt").isEqualTo(expected.getDeletedAt()))
            .satisfies(a -> assertThat(a.getDeletedBy()).as("check deletedBy").isEqualTo(expected.getDeletedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTripStatisticsUpdatableRelationshipsEquals(TripStatistics expected, TripStatistics actual) {
        // empty method
    }
}
