package com.ridehub.user.domain;

import static com.ridehub.user.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class UserStatisticsAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserStatisticsAllPropertiesEquals(UserStatistics expected, UserStatistics actual) {
        assertUserStatisticsAutoGeneratedPropertiesEquals(expected, actual);
        assertUserStatisticsAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserStatisticsAllUpdatablePropertiesEquals(UserStatistics expected, UserStatistics actual) {
        assertUserStatisticsUpdatableFieldsEquals(expected, actual);
        assertUserStatisticsUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserStatisticsAutoGeneratedPropertiesEquals(UserStatistics expected, UserStatistics actual) {
        assertThat(actual)
            .as("Verify UserStatistics auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserStatisticsUpdatableFieldsEquals(UserStatistics expected, UserStatistics actual) {
        assertThat(actual)
            .as("Verify UserStatistics relevant properties")
            .satisfies(a -> assertThat(a.getTotalTrips()).as("check totalTrips").isEqualTo(expected.getTotalTrips()))
            .satisfies(a ->
                assertThat(a.getTotalSpent())
                    .as("check totalSpent")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getTotalSpent())
            )
            .satisfies(a -> assertThat(a.getFavoriteRoutes()).as("check favoriteRoutes").isEqualTo(expected.getFavoriteRoutes()))
            .satisfies(a ->
                assertThat(a.getPreferredVehicleTypes()).as("check preferredVehicleTypes").isEqualTo(expected.getPreferredVehicleTypes())
            )
            .satisfies(a ->
                assertThat(a.getAverageTripDuration()).as("check averageTripDuration").isEqualTo(expected.getAverageTripDuration())
            )
            .satisfies(a -> assertThat(a.getLastTravelDate()).as("check lastTravelDate").isEqualTo(expected.getLastTravelDate()))
            .satisfies(a -> assertThat(a.getBookingFrequency()).as("check bookingFrequency").isEqualTo(expected.getBookingFrequency()))
            .satisfies(a -> assertThat(a.getLoyaltyPoints()).as("check loyaltyPoints").isEqualTo(expected.getLoyaltyPoints()))
            .satisfies(a -> assertThat(a.getMostFrequentOrigin()).as("check mostFrequentOrigin").isEqualTo(expected.getMostFrequentOrigin())
            )
            .satisfies(a ->
                assertThat(a.getMostFrequentDestination())
                    .as("check mostFrequentDestination")
                    .isEqualTo(expected.getMostFrequentDestination())
            )
            .satisfies(a ->
                assertThat(a.getAverageTripDistance())
                    .as("check averageTripDistance")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getAverageTripDistance())
            )
            .satisfies(a -> assertThat(a.getPeakTravelTime()).as("check peakTravelTime").isEqualTo(expected.getPeakTravelTime()))
            .satisfies(a -> assertThat(a.getWeekendTrips()).as("check weekendTrips").isEqualTo(expected.getWeekendTrips()))
            .satisfies(a -> assertThat(a.getHolidayTrips()).as("check holidayTrips").isEqualTo(expected.getHolidayTrips()))
            .satisfies(a -> assertThat(a.getCancelledTrips()).as("check cancelledTrips").isEqualTo(expected.getCancelledTrips()))
            .satisfies(a ->
                assertThat(a.getOnTimePerformanceRate())
                    .as("check onTimePerformanceRate")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getOnTimePerformanceRate())
            )
            .satisfies(a -> assertThat(a.getPreferredSeatTypes()).as("check preferredSeatTypes").isEqualTo(expected.getPreferredSeatTypes())
            )
            .satisfies(a -> assertThat(a.getMonthlyTripCount()).as("check monthlyTripCount").isEqualTo(expected.getMonthlyTripCount()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getUpdatedAt()).as("check updatedAt").isEqualTo(expected.getUpdatedAt()))
            .satisfies(a -> assertThat(a.getIsDeleted()).as("check isDeleted").isEqualTo(expected.getIsDeleted()))
            .satisfies(a -> assertThat(a.getDeletedAt()).as("check deletedAt").isEqualTo(expected.getDeletedAt()))
            .satisfies(a -> assertThat(a.getDeletedBy()).as("check deletedBy").isEqualTo(expected.getDeletedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertUserStatisticsUpdatableRelationshipsEquals(UserStatistics expected, UserStatistics actual) {
        // empty method
    }
}
